using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using Wacton.Unicolour.Datasets;
using static Wacton.Unicolour.Datasets.Xkcd;

namespace Wacton.Unicolour.Tests;

public class DatasetXkcdTests
{
    // https://xkcd.com/color/rgb.txt
    private static readonly Dictionary<string, string> HexLookup = new()
    {
        { "acid green", "#8ffe09" }, 
        { "adobe", "#bd6c48" }, 
        { "algae green", "#21c36f" }, 
        { "algae", "#54ac68" }, 
        { "almost black", "#070d0d" }, 
        { "amber", "#feb308" }, 
        { "amethyst", "#9b5fc0" }, 
        { "apple green", "#76cd26" }, 
        { "apple", "#6ecb3c" }, 
        { "apricot", "#ffb16d" }, 
        { "aqua blue", "#02d8e9" }, 
        { "aqua green", "#12e193" }, 
        { "aqua marine", "#2ee8bb" }, 
        { "aqua", "#13eac9" }, 
        { "aquamarine", "#04d8b2" }, 
        { "army green", "#4b5d16" }, 
        { "asparagus", "#77ab56" }, 
        { "aubergine", "#3d0734" }, 
        { "auburn", "#9a3001" }, 
        { "avocado green", "#87a922" }, 
        { "avocado", "#90b134" }, 
        { "azul", "#1d5dec" }, 
        { "azure", "#069af3" }, 
        { "baby blue", "#a2cffe" }, 
        { "baby green", "#8cff9e" }, 
        { "baby pink", "#ffb7ce" }, 
        { "baby poo", "#ab9004" }, 
        { "baby poop green", "#8f9805" }, 
        { "baby poop", "#937c00" }, 
        { "baby puke green", "#b6c406" }, 
        { "baby purple", "#ca9bf7" }, 
        { "baby shit brown", "#ad900d" }, 
        { "baby shit green", "#889717" }, 
        { "banana yellow", "#fafe4b" }, 
        { "banana", "#ffff7e" }, 
        { "barbie pink", "#fe46a5" }, 
        { "barf green", "#94ac02" }, 
        { "barney purple", "#a00498" }, 
        { "barney", "#ac1db8" }, 
        { "battleship grey", "#6b7c85" }, 
        { "beige", "#e6daa6" }, 
        { "berry", "#990f4b" }, 
        { "bile", "#b5c306" }, 
        { "black", "#000000" }, 
        { "bland", "#afa88b" }, 
        { "blood orange", "#fe4b03" }, 
        { "blood red", "#980002" }, 
        { "blood", "#770001" }, 
        { "blue blue", "#2242c7" }, 
        { "blue green", "#137e6d" }, 
        { "blue grey", "#607c8e" }, 
        { "blue purple", "#5729ce" }, 
        { "blue violet", "#5d06e9" }, 
        { "blue with a hint of purple", "#533cc6" }, 
        { "blue", "#0343df" }, 
        { "blue/green", "#0f9b8e" }, 
        { "blue/grey", "#758da3" }, 
        { "blue/purple", "#5a06ef" }, 
        { "blueberry", "#464196" }, 
        { "bluegreen", "#017a79" }, 
        { "bluegrey", "#85a3b2" }, 
        { "bluey green", "#2bb179" }, 
        { "bluey grey", "#89a0b0" }, 
        { "bluey purple", "#6241c7" }, 
        { "bluish green", "#10a674" }, 
        { "bluish grey", "#748b97" }, 
        { "bluish purple", "#703be7" }, 
        { "bluish", "#2976bb" }, 
        { "blurple", "#5539cc" }, 
        { "blush pink", "#fe828c" }, 
        { "blush", "#f29e8e" }, 
        { "booger green", "#96b403" }, 
        { "booger", "#9bb53c" }, 
        { "bordeaux", "#7b002c" }, 
        { "boring green", "#63b365" }, 
        { "bottle green", "#044a05" }, 
        { "brick orange", "#c14a09" }, 
        { "brick red", "#8f1402" }, 
        { "brick", "#a03623" }, 
        { "bright aqua", "#0bf9ea" }, 
        { "bright blue", "#0165fc" }, 
        { "bright cyan", "#41fdfe" }, 
        { "bright green", "#01ff07" }, 
        { "bright lavender", "#c760ff" }, 
        { "bright light blue", "#26f7fd" }, 
        { "bright light green", "#2dfe54" }, 
        { "bright lilac", "#c95efb" }, 
        { "bright lime green", "#65fe08" }, 
        { "bright lime", "#87fd05" }, 
        { "bright magenta", "#ff08e8" }, 
        { "bright olive", "#9cbb04" }, 
        { "bright orange", "#ff5b00" }, 
        { "bright pink", "#fe01b1" }, 
        { "bright purple", "#be03fd" }, 
        { "bright red", "#ff000d" }, 
        { "bright sea green", "#05ffa6" }, 
        { "bright sky blue", "#02ccfe" }, 
        { "bright teal", "#01f9c6" }, 
        { "bright turquoise", "#0ffef9" }, 
        { "bright violet", "#ad0afd" }, 
        { "bright yellow green", "#9dff00" }, 
        { "bright yellow", "#fffd01" }, 
        { "british racing green", "#05480d" }, 
        { "bronze", "#a87900" }, 
        { "brown green", "#706c11" }, 
        { "brown grey", "#8d8468" }, 
        { "brown orange", "#b96902" }, 
        { "brown red", "#922b05" }, 
        { "brown yellow", "#b29705" }, 
        { "brown", "#653700" }, 
        { "brownish green", "#6a6e09" }, 
        { "brownish grey", "#86775f" }, 
        { "brownish orange", "#cb7723" }, 
        { "brownish pink", "#c27e79" }, 
        { "brownish purple", "#76424e" }, 
        { "brownish red", "#9e3623" }, 
        { "brownish yellow", "#c9b003" }, 
        { "brownish", "#9c6d57" }, 
        { "browny green", "#6f6c0a" }, 
        { "browny orange", "#ca6b02" }, 
        { "bruise", "#7e4071" }, 
        { "bubble gum pink", "#ff69af" }, 
        { "bubblegum pink", "#fe83cc" }, 
        { "bubblegum", "#ff6cb5" }, 
        { "buff", "#fef69e" }, 
        { "burgundy", "#610023" }, 
        { "burnt orange", "#c04e01" }, 
        { "burnt red", "#9f2305" }, 
        { "burnt siena", "#b75203" }, 
        { "burnt sienna", "#b04e0f" }, 
        { "burnt umber", "#a0450e" }, 
        { "burnt yellow", "#d5ab09" }, 
        { "burple", "#6832e3" }, 
        { "butter yellow", "#fffd74" }, 
        { "butter", "#ffff81" }, 
        { "butterscotch", "#fdb147" }, 
        { "cadet blue", "#4e7496" }, 
        { "camel", "#c69f59" }, 
        { "camo green", "#526525" }, 
        { "camo", "#7f8f4e" }, 
        { "camouflage green", "#4b6113" }, 
        { "canary yellow", "#fffe40" }, 
        { "canary", "#fdff63" }, 
        { "candy pink", "#ff63e9" }, 
        { "caramel", "#af6f09" }, 
        { "carmine", "#9d0216" }, 
        { "carnation pink", "#ff7fa7" }, 
        { "carnation", "#fd798f" }, 
        { "carolina blue", "#8ab8fe" }, 
        { "celadon", "#befdb7" }, 
        { "celery", "#c1fd95" }, 
        { "cement", "#a5a391" }, 
        { "cerise", "#de0c62" }, 
        { "cerulean blue", "#056eee" }, 
        { "cerulean", "#0485d1" }, 
        { "charcoal grey", "#3c4142" }, 
        { "charcoal", "#343837" }, 
        { "chartreuse", "#c1f80a" }, 
        { "cherry red", "#f7022a" }, 
        { "cherry", "#cf0234" }, 
        { "chestnut", "#742802" }, 
        { "chocolate brown", "#411900" }, 
        { "chocolate", "#3d1c02" }, 
        { "cinnamon", "#ac4f06" }, 
        { "claret", "#680018" }, 
        { "clay brown", "#b2713d" }, 
        { "clay", "#b66a50" }, 
        { "clear blue", "#247afd" }, 
        { "cloudy blue", "#acc2d9" }, 
        { "cobalt blue", "#030aa7" }, 
        { "cobalt", "#1e488f" }, 
        { "cocoa", "#875f42" }, 
        { "coffee", "#a6814c" }, 
        { "cool blue", "#4984b8" }, 
        { "cool green", "#33b864" }, 
        { "cool grey", "#95a3a6" }, 
        { "copper", "#b66325" }, 
        { "coral pink", "#ff6163" }, 
        { "coral", "#fc5a50" }, 
        { "cornflower blue", "#5170d7" }, 
        { "cornflower", "#6a79f7" }, 
        { "cranberry", "#9e003a" }, 
        { "cream", "#ffffc2" }, 
        { "creme", "#ffffb6" }, 
        { "crimson", "#8c000f" }, 
        { "custard", "#fffd78" }, 
        { "cyan", "#00ffff" }, 
        { "dandelion", "#fedf08" }, 
        { "dark aqua", "#05696b" }, 
        { "dark aquamarine", "#017371" }, 
        { "dark beige", "#ac9362" }, 
        { "dark blue green", "#005249" }, 
        { "dark blue grey", "#1f3b4d" }, 
        { "dark blue", "#00035b" }, 
        { "dark brown", "#341c02" }, 
        { "dark coral", "#cf524e" }, 
        { "dark cream", "#fff39a" }, 
        { "dark cyan", "#0a888a" }, 
        { "dark forest green", "#002d04" }, 
        { "dark fuchsia", "#9d0759" }, 
        { "dark gold", "#b59410" }, 
        { "dark grass green", "#388004" }, 
        { "dark green blue", "#1f6357" }, 
        { "dark green", "#033500" }, 
        { "dark grey blue", "#29465b" }, 
        { "dark grey", "#363737" }, 
        { "dark hot pink", "#d90166" }, 
        { "dark indigo", "#1f0954" }, 
        { "dark khaki", "#9b8f55" }, 
        { "dark lavender", "#856798" }, 
        { "dark lilac", "#9c6da5" }, 
        { "dark lime green", "#7ebd01" }, 
        { "dark lime", "#84b701" }, 
        { "dark magenta", "#960056" }, 
        { "dark maroon", "#3c0008" }, 
        { "dark mauve", "#874c62" }, 
        { "dark mint green", "#20c073" }, 
        { "dark mint", "#48c072" }, 
        { "dark mustard", "#a88905" }, 
        { "dark navy blue", "#00022e" }, 
        { "dark navy", "#000435" }, 
        { "dark olive green", "#3c4d03" }, 
        { "dark olive", "#373e02" }, 
        { "dark orange", "#c65102" }, 
        { "dark pastel green", "#56ae57" }, 
        { "dark peach", "#de7e5d" }, 
        { "dark periwinkle", "#665fd1" }, 
        { "dark pink", "#cb416b" }, 
        { "dark plum", "#3f012c" }, 
        { "dark purple", "#35063e" }, 
        { "dark red", "#840000" }, 
        { "dark rose", "#b5485d" }, 
        { "dark royal blue", "#02066f" }, 
        { "dark sage", "#598556" }, 
        { "dark salmon", "#c85a53" }, 
        { "dark sand", "#a88f59" }, 
        { "dark sea green", "#11875d" }, 
        { "dark seafoam green", "#3eaf76" }, 
        { "dark seafoam", "#1fb57a" }, 
        { "dark sky blue", "#448ee4" }, 
        { "dark slate blue", "#214761" }, 
        { "dark tan", "#af884a" }, 
        { "dark taupe", "#7f684e" }, 
        { "dark teal", "#014d4e" }, 
        { "dark turquoise", "#045c5a" }, 
        { "dark violet", "#34013f" }, 
        { "dark yellow green", "#728f02" }, 
        { "dark yellow", "#d5b60a" }, 
        { "dark", "#1b2431" }, 
        { "darkblue", "#030764" }, 
        { "darkgreen", "#054907" }, 
        { "darkish blue", "#014182" }, 
        { "darkish green", "#287c37" }, 
        { "darkish pink", "#da467d" }, 
        { "darkish purple", "#751973" }, 
        { "darkish red", "#a90308" }, 
        { "deep aqua", "#08787f" }, 
        { "deep blue", "#040273" }, 
        { "deep brown", "#410200" }, 
        { "deep green", "#02590f" }, 
        { "deep lavender", "#8d5eb7" }, 
        { "deep lilac", "#966ebd" }, 
        { "deep magenta", "#a0025c" }, 
        { "deep orange", "#dc4d01" }, 
        { "deep pink", "#cb0162" }, 
        { "deep purple", "#36013f" }, 
        { "deep red", "#9a0200" }, 
        { "deep rose", "#c74767" }, 
        { "deep sea blue", "#015482" }, 
        { "deep sky blue", "#0d75f8" }, 
        { "deep teal", "#00555a" }, 
        { "deep turquoise", "#017374" }, 
        { "deep violet", "#490648" }, 
        { "denim blue", "#3b5b92" }, 
        { "denim", "#3b638c" }, 
        { "desert", "#ccad60" }, 
        { "diarrhea", "#9f8303" }, 
        { "dirt brown", "#836539" }, 
        { "dirt", "#8a6e45" }, 
        { "dirty blue", "#3f829d" }, 
        { "dirty green", "#667e2c" }, 
        { "dirty orange", "#c87606" }, 
        { "dirty pink", "#ca7b80" }, 
        { "dirty purple", "#734a65" }, 
        { "dirty yellow", "#cdc50a" }, 
        { "dodger blue", "#3e82fc" }, 
        { "drab green", "#749551" }, 
        { "drab", "#828344" }, 
        { "dried blood", "#4b0101" }, 
        { "duck egg blue", "#c3fbf4" }, 
        { "dull blue", "#49759c" }, 
        { "dull brown", "#876e4b" }, 
        { "dull green", "#74a662" }, 
        { "dull orange", "#d8863b" }, 
        { "dull pink", "#d5869d" }, 
        { "dull purple", "#84597e" }, 
        { "dull red", "#bb3f3f" }, 
        { "dull teal", "#5f9e8f" }, 
        { "dull yellow", "#eedc5b" }, 
        { "dusk blue", "#26538d" }, 
        { "dusk", "#4e5481" }, 
        { "dusky blue", "#475f94" }, 
        { "dusky pink", "#cc7a8b" }, 
        { "dusky purple", "#895b7b" }, 
        { "dusky rose", "#ba6873" }, 
        { "dust", "#b2996e" }, 
        { "dusty blue", "#5a86ad" }, 
        { "dusty green", "#76a973" }, 
        { "dusty lavender", "#ac86a8" }, 
        { "dusty orange", "#f0833a" }, 
        { "dusty pink", "#d58a94" }, 
        { "dusty purple", "#825f87" }, 
        { "dusty red", "#b9484e" }, 
        { "dusty rose", "#c0737a" }, 
        { "dusty teal", "#4c9085" }, 
        { "earth", "#a2653e" }, 
        { "easter green", "#8cfd7e" }, 
        { "easter purple", "#c071fe" }, 
        { "ecru", "#feffca" }, 
        { "egg shell", "#fffcc4" }, 
        { "eggplant purple", "#430541" }, 
        { "eggplant", "#380835" }, 
        { "eggshell blue", "#c4fff7" }, 
        { "eggshell", "#ffffd4" }, 
        { "electric blue", "#0652ff" }, 
        { "electric green", "#21fc0d" }, 
        { "electric lime", "#a8ff04" }, 
        { "electric pink", "#ff0490" }, 
        { "electric purple", "#aa23ff" }, 
        { "emerald green", "#028f1e" }, 
        { "emerald", "#01a049" }, 
        { "evergreen", "#05472a" }, 
        { "faded blue", "#658cbb" }, 
        { "faded green", "#7bb274" }, 
        { "faded orange", "#f0944d" }, 
        { "faded pink", "#de9dac" }, 
        { "faded purple", "#916e99" }, 
        { "faded red", "#d3494e" }, 
        { "faded yellow", "#feff7f" }, 
        { "fawn", "#cfaf7b" }, 
        { "fern green", "#548d44" }, 
        { "fern", "#63a950" }, 
        { "fire engine red", "#fe0002" }, 
        { "flat blue", "#3c73a8" }, 
        { "flat green", "#699d4c" }, 
        { "fluorescent green", "#08ff08" }, 
        { "fluro green", "#0aff02" }, 
        { "foam green", "#90fda9" }, 
        { "forest green", "#06470c" }, 
        { "forest", "#0b5509" }, 
        { "forrest green", "#154406" }, 
        { "french blue", "#436bad" }, 
        { "fresh green", "#69d84f" }, 
        { "frog green", "#58bc08" }, 
        { "fuchsia", "#ed0dd9" }, 
        { "gold", "#dbb40c" }, 
        { "golden brown", "#b27a01" }, 
        { "golden rod", "#f9bc08" }, 
        { "golden yellow", "#fec615" }, 
        { "golden", "#f5bf03" }, 
        { "goldenrod", "#fac205" }, 
        { "grape purple", "#5d1451" }, 
        { "grape", "#6c3461" }, 
        { "grapefruit", "#fd5956" }, 
        { "grass green", "#3f9b0b" }, 
        { "grass", "#5cac2d" }, 
        { "grassy green", "#419c03" }, 
        { "green apple", "#5edc1f" }, 
        { "green blue", "#06b48b" }, 
        { "green brown", "#544e03" }, 
        { "green grey", "#77926f" }, 
        { "green teal", "#0cb577" }, 
        { "green yellow", "#c9ff27" }, 
        { "green", "#15b01a" }, 
        { "green/blue", "#01c08d" }, 
        { "green/yellow", "#b5ce08" }, 
        { "greenblue", "#23c48b" }, 
        { "greenish beige", "#c9d179" }, 
        { "greenish blue", "#0b8b87" }, 
        { "greenish brown", "#696112" }, 
        { "greenish cyan", "#2afeb7" }, 
        { "greenish grey", "#96ae8d" }, 
        { "greenish tan", "#bccb7a" }, 
        { "greenish teal", "#32bf84" }, 
        { "greenish turquoise", "#00fbb0" }, 
        { "greenish yellow", "#cdfd02" }, 
        { "greenish", "#40a368" }, 
        { "greeny blue", "#42b395" }, 
        { "greeny brown", "#696006" }, 
        { "greeny grey", "#7ea07a" }, 
        { "greeny yellow", "#c6f808" }, 
        { "grey blue", "#6b8ba4" }, 
        { "grey brown", "#7f7053" }, 
        { "grey green", "#789b73" }, 
        { "grey pink", "#c3909b" }, 
        { "grey purple", "#826d8c" }, 
        { "grey teal", "#5e9b8a" }, 
        { "grey", "#929591" }, 
        { "grey/blue", "#647d8e" }, 
        { "grey/green", "#86a17d" }, 
        { "greyblue", "#77a1b5" }, 
        { "greyish blue", "#5e819d" }, 
        { "greyish brown", "#7a6a4f" }, 
        { "greyish green", "#82a67d" }, 
        { "greyish pink", "#c88d94" }, 
        { "greyish purple", "#887191" }, 
        { "greyish teal", "#719f91" }, 
        { "greyish", "#a8a495" }, 
        { "gross green", "#a0bf16" }, 
        { "gunmetal", "#536267" }, 
        { "hazel", "#8e7618" }, 
        { "heather", "#a484ac" }, 
        { "heliotrope", "#d94ff5" }, 
        { "highlighter green", "#1bfc06" }, 
        { "hospital green", "#9be5aa" }, 
        { "hot green", "#25ff29" }, 
        { "hot magenta", "#f504c9" }, 
        { "hot pink", "#ff028d" }, 
        { "hot purple", "#cb00f5" }, 
        { "hunter green", "#0b4008" }, 
        { "ice blue", "#d7fffe" }, 
        { "ice", "#d6fffa" }, 
        { "icky green", "#8fae22" }, 
        { "indian red", "#850e04" }, 
        { "indigo blue", "#3a18b1" }, 
        { "indigo", "#380282" }, 
        { "iris", "#6258c4" }, 
        { "irish green", "#019529" }, 
        { "ivory", "#ffffcb" }, 
        { "jade green", "#2baf6a" }, 
        { "jade", "#1fa774" }, 
        { "jungle green", "#048243" }, 
        { "kelley green", "#009337" }, 
        { "kelly green", "#02ab2e" }, 
        { "kermit green", "#5cb200" }, 
        { "key lime", "#aeff6e" }, 
        { "khaki green", "#728639" }, 
        { "khaki", "#aaa662" }, 
        { "kiwi green", "#8ee53f" }, 
        { "kiwi", "#9cef43" }, 
        { "lavender blue", "#8b88f8" }, 
        { "lavender pink", "#dd85d7" }, 
        { "lavender", "#c79fef" }, 
        { "lawn green", "#4da409" }, 
        { "leaf green", "#5ca904" }, 
        { "leaf", "#71aa34" }, 
        { "leafy green", "#51b73b" }, 
        { "leather", "#ac7434" }, 
        { "lemon green", "#adf802" }, 
        { "lemon lime", "#bffe28" }, 
        { "lemon yellow", "#fdff38" }, 
        { "lemon", "#fdff52" }, 
        { "lichen", "#8fb67b" }, 
        { "light aqua", "#8cffdb" }, 
        { "light aquamarine", "#7bfdc7" }, 
        { "light beige", "#fffeb6" }, 
        { "light blue green", "#7efbb3" }, 
        { "light blue grey", "#b7c9e2" }, 
        { "light blue", "#95d0fc" }, 
        { "light bluish green", "#76fda8" }, 
        { "light bright green", "#53fe5c" }, 
        { "light brown", "#ad8150" }, 
        { "light burgundy", "#a8415b" }, 
        { "light cyan", "#acfffc" }, 
        { "light eggplant", "#894585" }, 
        { "light forest green", "#4f9153" }, 
        { "light gold", "#fddc5c" }, 
        { "light grass green", "#9af764" }, 
        { "light green blue", "#56fca2" }, 
        { "light green", "#96f97b" }, 
        { "light greenish blue", "#63f7b4" }, 
        { "light grey blue", "#9dbcd4" }, 
        { "light grey green", "#b7e1a1" }, 
        { "light grey", "#d8dcd6" }, 
        { "light indigo", "#6d5acf" }, 
        { "light khaki", "#e6f2a2" }, 
        { "light lavendar", "#efc0fe" }, 
        { "light lavender", "#dfc5fe" }, 
        { "light light blue", "#cafffb" }, 
        { "light light green", "#c8ffb0" }, 
        { "light lilac", "#edc8ff" }, 
        { "light lime green", "#b9ff66" }, 
        { "light lime", "#aefd6c" }, 
        { "light magenta", "#fa5ff7" }, 
        { "light maroon", "#a24857" }, 
        { "light mauve", "#c292a1" }, 
        { "light mint green", "#a6fbb2" }, 
        { "light mint", "#b6ffbb" }, 
        { "light moss green", "#a6c875" }, 
        { "light mustard", "#f7d560" }, 
        { "light navy blue", "#2e5a88" }, 
        { "light navy", "#155084" }, 
        { "light neon green", "#4efd54" }, 
        { "light olive green", "#a4be5c" }, 
        { "light olive", "#acbf69" }, 
        { "light orange", "#fdaa48" }, 
        { "light pastel green", "#b2fba5" }, 
        { "light pea green", "#c4fe82" }, 
        { "light peach", "#ffd8b1" }, 
        { "light periwinkle", "#c1c6fc" }, 
        { "light pink", "#ffd1df" }, 
        { "light plum", "#9d5783" }, 
        { "light purple", "#bf77f6" }, 
        { "light red", "#ff474c" }, 
        { "light rose", "#ffc5cb" }, 
        { "light royal blue", "#3a2efe" }, 
        { "light sage", "#bcecac" }, 
        { "light salmon", "#fea993" }, 
        { "light sea green", "#98f6b0" }, 
        { "light seafoam green", "#a7ffb5" }, 
        { "light seafoam", "#a0febf" }, 
        { "light sky blue", "#c6fcff" }, 
        { "light tan", "#fbeeac" }, 
        { "light teal", "#90e4c1" }, 
        { "light turquoise", "#7ef4cc" }, 
        { "light urple", "#b36ff6" }, 
        { "light violet", "#d6b4fc" }, 
        { "light yellow green", "#ccfd7f" }, 
        { "light yellow", "#fffe7a" }, 
        { "light yellowish green", "#c2ff89" }, 
        { "lightblue", "#7bc8f6" }, 
        { "lighter green", "#75fd63" }, 
        { "lighter purple", "#a55af4" }, 
        { "lightgreen", "#76ff7b" }, 
        { "lightish blue", "#3d7afd" }, 
        { "lightish green", "#61e160" }, 
        { "lightish purple", "#a552e6" }, 
        { "lightish red", "#fe2f4a" }, 
        { "lilac", "#cea2fd" }, 
        { "liliac", "#c48efd" }, 
        { "lime green", "#89fe05" }, 
        { "lime yellow", "#d0fe1d" }, 
        { "lime", "#aaff32" }, 
        { "lipstick red", "#c0022f" }, 
        { "lipstick", "#d5174e" }, 
        { "macaroni and cheese", "#efb435" }, 
        { "magenta", "#c20078" }, 
        { "mahogany", "#4a0100" }, 
        { "maize", "#f4d054" }, 
        { "mango", "#ffa62b" }, 
        { "manilla", "#fffa86" }, 
        { "marigold", "#fcc006" }, 
        { "marine blue", "#01386a" }, 
        { "marine", "#042e60" }, 
        { "maroon", "#650021" }, 
        { "mauve", "#ae7181" }, 
        { "medium blue", "#2c6fbb" }, 
        { "medium brown", "#7f5112" }, 
        { "medium green", "#39ad48" }, 
        { "medium grey", "#7d7f7c" }, 
        { "medium pink", "#f36196" }, 
        { "medium purple", "#9e43a2" }, 
        { "melon", "#ff7855" }, 
        { "merlot", "#730039" }, 
        { "metallic blue", "#4f738e" }, 
        { "mid blue", "#276ab3" }, 
        { "mid green", "#50a747" }, 
        { "midnight blue", "#020035" }, 
        { "midnight purple", "#280137" }, 
        { "midnight", "#03012d" }, 
        { "military green", "#667c3e" }, 
        { "milk chocolate", "#7f4e1e" }, 
        { "mint green", "#8fff9f" }, 
        { "mint", "#9ffeb0" }, 
        { "minty green", "#0bf77d" }, 
        { "mocha", "#9d7651" }, 
        { "moss green", "#658b38" }, 
        { "moss", "#769958" }, 
        { "mossy green", "#638b27" }, 
        { "mud brown", "#60460f" }, 
        { "mud green", "#606602" }, 
        { "mud", "#735c12" }, 
        { "muddy brown", "#886806" }, 
        { "muddy green", "#657432" }, 
        { "muddy yellow", "#bfac05" }, 
        { "mulberry", "#920a4e" }, 
        { "murky green", "#6c7a0e" }, 
        { "mushroom", "#ba9e88" }, 
        { "mustard brown", "#ac7e04" }, 
        { "mustard green", "#a8b504" }, 
        { "mustard yellow", "#d2bd0a" }, 
        { "mustard", "#ceb301" }, 
        { "muted blue", "#3b719f" }, 
        { "muted green", "#5fa052" }, 
        { "muted pink", "#d1768f" }, 
        { "muted purple", "#805b87" }, 
        { "nasty green", "#70b23f" }, 
        { "navy blue", "#001146" }, 
        { "navy green", "#35530a" }, 
        { "navy", "#01153e" }, 
        { "neon blue", "#04d9ff" }, 
        { "neon green", "#0cff0c" }, 
        { "neon pink", "#fe019a" }, 
        { "neon purple", "#bc13fe" }, 
        { "neon red", "#ff073a" }, 
        { "neon yellow", "#cfff04" }, 
        { "nice blue", "#107ab0" }, 
        { "night blue", "#040348" }, 
        { "ocean blue", "#03719c" }, 
        { "ocean green", "#3d9973" }, 
        { "ocean", "#017b92" }, 
        { "ocher", "#bf9b0c" }, 
        { "ochre", "#bf9005" }, 
        { "ocre", "#c69c04" }, 
        { "off blue", "#5684ae" }, 
        { "off green", "#6ba353" }, 
        { "off white", "#ffffe4" }, 
        { "off yellow", "#f1f33f" }, 
        { "old pink", "#c77986" }, 
        { "old rose", "#c87f89" }, 
        { "olive brown", "#645403" }, 
        { "olive drab", "#6f7632" }, 
        { "olive green", "#677a04" }, 
        { "olive yellow", "#c2b709" }, 
        { "olive", "#6e750e" }, 
        { "orange brown", "#be6400" }, 
        { "orange pink", "#ff6f52" }, 
        { "orange red", "#fd411e" }, 
        { "orange yellow", "#ffad01" }, 
        { "orange", "#f97306" }, 
        { "orangeish", "#fd8d49" }, 
        { "orangered", "#fe420f" }, 
        { "orangey brown", "#b16002" }, 
        { "orangey red", "#fa4224" }, 
        { "orangey yellow", "#fdb915" }, 
        { "orangish brown", "#b25f03" }, 
        { "orangish red", "#f43605" }, 
        { "orangish", "#fc824a" }, 
        { "orchid", "#c875c4" }, 
        { "pale aqua", "#b8ffeb" }, 
        { "pale blue", "#d0fefe" }, 
        { "pale brown", "#b1916e" }, 
        { "pale cyan", "#b7fffa" }, 
        { "pale gold", "#fdde6c" }, 
        { "pale green", "#c7fdb5" }, 
        { "pale grey", "#fdfdfe" }, 
        { "pale lavender", "#eecffe" }, 
        { "pale light green", "#b1fc99" }, 
        { "pale lilac", "#e4cbff" }, 
        { "pale lime green", "#b1ff65" }, 
        { "pale lime", "#befd73" }, 
        { "pale magenta", "#d767ad" }, 
        { "pale mauve", "#fed0fc" }, 
        { "pale olive green", "#b1d27b" }, 
        { "pale olive", "#b9cc81" }, 
        { "pale orange", "#ffa756" }, 
        { "pale peach", "#ffe5ad" }, 
        { "pale pink", "#ffcfdc" }, 
        { "pale purple", "#b790d4" }, 
        { "pale red", "#d9544d" }, 
        { "pale rose", "#fdc1c5" }, 
        { "pale salmon", "#ffb19a" }, 
        { "pale sky blue", "#bdf6fe" }, 
        { "pale teal", "#82cbb2" }, 
        { "pale turquoise", "#a5fbd5" }, 
        { "pale violet", "#ceaefa" }, 
        { "pale yellow", "#ffff84" }, 
        { "pale", "#fff9d0" }, 
        { "parchment", "#fefcaf" }, 
        { "pastel blue", "#a2bffe" }, 
        { "pastel green", "#b0ff9d" }, 
        { "pastel orange", "#ff964f" }, 
        { "pastel pink", "#ffbacd" }, 
        { "pastel purple", "#caa0ff" }, 
        { "pastel red", "#db5856" }, 
        { "pastel yellow", "#fffe71" }, 
        { "pea green", "#8eab12" }, 
        { "pea soup green", "#94a617" }, 
        { "pea soup", "#929901" }, 
        { "pea", "#a4bf20" }, 
        { "peach", "#ffb07c" }, 
        { "peachy pink", "#ff9a8a" }, 
        { "peacock blue", "#016795" }, 
        { "pear", "#cbf85f" }, 
        { "periwinkle blue", "#8f99fb" }, 
        { "periwinkle", "#8e82fe" }, 
        { "perrywinkle", "#8f8ce7" }, 
        { "petrol", "#005f6a" }, 
        { "pig pink", "#e78ea5" }, 
        { "pine green", "#0a481e" }, 
        { "pine", "#2b5d34" }, 
        { "pink purple", "#db4bda" }, 
        { "pink red", "#f5054f" }, 
        { "pink", "#ff81c0" }, 
        { "pink/purple", "#ef1de7" }, 
        { "pinkish brown", "#b17261" }, 
        { "pinkish grey", "#c8aca9" }, 
        { "pinkish orange", "#ff724c" }, 
        { "pinkish purple", "#d648d7" }, 
        { "pinkish red", "#f10c45" }, 
        { "pinkish tan", "#d99b82" }, 
        { "pinkish", "#d46a7e" }, 
        { "pinky purple", "#c94cbe" }, 
        { "pinky red", "#fc2647" }, 
        { "pinky", "#fc86aa" }, 
        { "piss yellow", "#ddd618" }, 
        { "pistachio", "#c0fa8b" }, 
        { "plum purple", "#4e0550" }, 
        { "plum", "#580f41" }, 
        { "poison green", "#40fd14" }, 
        { "poo brown", "#885f01" }, 
        { "poo", "#8f7303" }, 
        { "poop brown", "#7a5901" }, 
        { "poop green", "#6f7c00" }, 
        { "poop", "#7f5e00" }, 
        { "powder blue", "#b1d1fc" }, 
        { "powder pink", "#ffb2d0" }, 
        { "primary blue", "#0804f9" }, 
        { "prussian blue", "#004577" }, 
        { "puce", "#a57e52" }, 
        { "puke brown", "#947706" }, 
        { "puke green", "#9aae07" }, 
        { "puke yellow", "#c2be0e" }, 
        { "puke", "#a5a502" }, 
        { "pumpkin orange", "#fb7d07" }, 
        { "pumpkin", "#e17701" }, 
        { "pure blue", "#0203e2" }, 
        { "purple blue", "#632de9" }, 
        { "purple brown", "#673a3f" }, 
        { "purple grey", "#866f85" }, 
        { "purple pink", "#e03fd8" }, 
        { "purple red", "#990147" }, 
        { "purple", "#7e1e9c" }, 
        { "purple/blue", "#5d21d0" }, 
        { "purple/pink", "#d725de" }, 
        { "purpleish blue", "#6140ef" }, 
        { "purpleish pink", "#df4ec8" }, 
        { "purpleish", "#98568d" }, 
        { "purpley blue", "#5f34e7" }, 
        { "purpley grey", "#947e94" }, 
        { "purpley pink", "#c83cb9" }, 
        { "purpley", "#8756e4" }, 
        { "purplish blue", "#601ef9" }, 
        { "purplish brown", "#6b4247" }, 
        { "purplish grey", "#7a687f" }, 
        { "purplish pink", "#ce5dae" }, 
        { "purplish red", "#b0054b" }, 
        { "purplish", "#94568c" }, 
        { "purply blue", "#661aee" }, 
        { "purply pink", "#f075e6" }, 
        { "purply", "#983fb2" }, 
        { "putty", "#beae8a" }, 
        { "racing green", "#014600" }, 
        { "radioactive green", "#2cfa1f" }, 
        { "raspberry", "#b00149" }, 
        { "raw sienna", "#9a6200" }, 
        { "raw umber", "#a75e09" }, 
        { "really light blue", "#d4ffff" }, 
        { "red brown", "#8b2e16" }, 
        { "red orange", "#fd3c06" }, 
        { "red pink", "#fa2a55" }, 
        { "red purple", "#820747" }, 
        { "red violet", "#9e0168" }, 
        { "red wine", "#8c0034" }, 
        { "red", "#e50000" }, 
        { "reddish brown", "#7f2b0a" }, 
        { "reddish grey", "#997570" }, 
        { "reddish orange", "#f8481c" }, 
        { "reddish pink", "#fe2c54" }, 
        { "reddish purple", "#910951" }, 
        { "reddish", "#c44240" }, 
        { "reddy brown", "#6e1005" }, 
        { "rich blue", "#021bf9" }, 
        { "rich purple", "#720058" }, 
        { "robin egg blue", "#8af1fe" }, 
        { "robin's egg blue", "#98eff9" }, 
        { "robin's egg", "#6dedfd" }, 
        { "rosa", "#fe86a4" }, 
        { "rose pink", "#f7879a" }, 
        { "rose red", "#be013c" }, 
        { "rose", "#cf6275" }, 
        { "rosy pink", "#f6688e" }, 
        { "rouge", "#ab1239" }, 
        { "royal blue", "#0504aa" }, 
        { "royal purple", "#4b006e" }, 
        { "royal", "#0c1793" }, 
        { "ruby", "#ca0147" }, 
        { "russet", "#a13905" }, 
        { "rust brown", "#8b3103" }, 
        { "rust orange", "#c45508" }, 
        { "rust red", "#aa2704" }, 
        { "rust", "#a83c09" }, 
        { "rusty orange", "#cd5909" }, 
        { "rusty red", "#af2f0d" }, 
        { "saffron", "#feb209" }, 
        { "sage green", "#88b378" }, 
        { "sage", "#87ae73" }, 
        { "salmon pink", "#fe7b7c" }, 
        { "salmon", "#ff796c" }, 
        { "sand brown", "#cba560" }, 
        { "sand yellow", "#fce166" }, 
        { "sand", "#e2ca76" }, 
        { "sandstone", "#c9ae74" }, 
        { "sandy brown", "#c4a661" }, 
        { "sandy yellow", "#fdee73" }, 
        { "sandy", "#f1da7a" }, 
        { "sap green", "#5c8b15" }, 
        { "sapphire", "#2138ab" }, 
        { "scarlet", "#be0119" }, 
        { "sea blue", "#047495" }, 
        { "sea green", "#53fca1" }, 
        { "sea", "#3c9992" }, 
        { "seafoam blue", "#78d1b6" }, 
        { "seafoam green", "#7af9ab" }, 
        { "seafoam", "#80f9ad" }, 
        { "seaweed green", "#35ad6b" }, 
        { "seaweed", "#18d17b" }, 
        { "sepia", "#985e2b" }, 
        { "shamrock green", "#02c14d" }, 
        { "shamrock", "#01b44c" }, 
        { "shit brown", "#7b5804" }, 
        { "shit green", "#758000" }, 
        { "shit", "#7f5f00" }, 
        { "shocking pink", "#fe02a2" }, 
        { "sick green", "#9db92c" }, 
        { "sickly green", "#94b21c" }, 
        { "sickly yellow", "#d0e429" }, 
        { "sienna", "#a9561e" }, 
        { "silver", "#c5c9c7" }, 
        { "sky blue", "#75bbfd" }, 
        { "sky", "#82cafc" }, 
        { "slate blue", "#5b7c99" }, 
        { "slate green", "#658d6d" }, 
        { "slate grey", "#59656d" }, 
        { "slate", "#516572" }, 
        { "slime green", "#99cc04" }, 
        { "snot green", "#9dc100" }, 
        { "snot", "#acbb0d" }, 
        { "soft blue", "#6488ea" }, 
        { "soft green", "#6fc276" }, 
        { "soft pink", "#fdb0c0" }, 
        { "soft purple", "#a66fb5" }, 
        { "spearmint", "#1ef876" }, 
        { "spring green", "#a9f971" }, 
        { "spruce", "#0a5f38" }, 
        { "squash", "#f2ab15" }, 
        { "steel blue", "#5a7d9a" }, 
        { "steel grey", "#6f828a" }, 
        { "steel", "#738595" }, 
        { "stone", "#ada587" }, 
        { "stormy blue", "#507b9c" }, 
        { "straw", "#fcf679" }, 
        { "strawberry", "#fb2943" }, 
        { "strong blue", "#0c06f7" }, 
        { "strong pink", "#ff0789" }, 
        { "sun yellow", "#ffdf22" }, 
        { "sunflower yellow", "#ffda03" }, 
        { "sunflower", "#ffc512" }, 
        { "sunny yellow", "#fff917" }, 
        { "sunshine yellow", "#fffd37" }, 
        { "swamp green", "#748500" }, 
        { "swamp", "#698339" }, 
        { "tan brown", "#ab7e4c" }, 
        { "tan green", "#a9be70" }, 
        { "tan", "#d1b26f" }, 
        { "tangerine", "#ff9408" }, 
        { "taupe", "#b9a281" }, 
        { "tea green", "#bdf8a3" }, 
        { "tea", "#65ab7c" }, 
        { "teal blue", "#01889f" }, 
        { "teal green", "#25a36f" }, 
        { "teal", "#029386" }, 
        { "tealish green", "#0cdc73" }, 
        { "tealish", "#24bca8" }, 
        { "terra cotta", "#c9643b" }, 
        { "terracota", "#cb6843" }, 
        { "terracotta", "#ca6641" }, 
        { "tiffany blue", "#7bf2da" }, 
        { "tomato red", "#ec2d01" }, 
        { "tomato", "#ef4026" }, 
        { "topaz", "#13bbaf" }, 
        { "toupe", "#c7ac7d" }, 
        { "toxic green", "#61de2a" }, 
        { "tree green", "#2a7e19" }, 
        { "true blue", "#010fcc" }, 
        { "true green", "#089404" }, 
        { "turquoise blue", "#06b1c4" }, 
        { "turquoise green", "#04f489" }, 
        { "turquoise", "#06c2ac" }, 
        { "turtle green", "#75b84f" }, 
        { "twilight blue", "#0a437a" }, 
        { "twilight", "#4e518b" }, 
        { "ugly blue", "#31668a" }, 
        { "ugly brown", "#7d7103" }, 
        { "ugly green", "#7a9703" }, 
        { "ugly pink", "#cd7584" }, 
        { "ugly purple", "#a442a0" }, 
        { "ugly yellow", "#d0c101" }, 
        { "ultramarine blue", "#1805db" }, 
        { "ultramarine", "#2000b1" }, 
        { "umber", "#b26400" }, 
        { "velvet", "#750851" }, 
        { "vermillion", "#f4320c" }, 
        { "very dark blue", "#000133" }, 
        { "very dark brown", "#1d0200" }, 
        { "very dark green", "#062e03" }, 
        { "very dark purple", "#2a0134" }, 
        { "very light blue", "#d5ffff" }, 
        { "very light brown", "#d3b683" }, 
        { "very light green", "#d1ffbd" }, 
        { "very light pink", "#fff4f2" }, 
        { "very light purple", "#f6cefc" }, 
        { "very pale blue", "#d6fffe" }, 
        { "very pale green", "#cffdbc" }, 
        { "vibrant blue", "#0339f8" }, 
        { "vibrant green", "#0add08" }, 
        { "vibrant purple", "#ad03de" }, 
        { "violet blue", "#510ac9" }, 
        { "violet pink", "#fb5ffc" }, 
        { "violet red", "#a50055" }, 
        { "violet", "#9a0eea" }, 
        { "viridian", "#1e9167" }, 
        { "vivid blue", "#152eff" }, 
        { "vivid green", "#2fef10" }, 
        { "vivid purple", "#9900fa" }, 
        { "vomit green", "#89a203" }, 
        { "vomit yellow", "#c7c10c" }, 
        { "vomit", "#a2a415" }, 
        { "warm blue", "#4b57db" }, 
        { "warm brown", "#964e02" }, 
        { "warm grey", "#978a84" }, 
        { "warm pink", "#fb5581" }, 
        { "warm purple", "#952e8f" }, 
        { "washed out green", "#bcf5a6" }, 
        { "water blue", "#0e87cc" }, 
        { "watermelon", "#fd4659" }, 
        { "weird green", "#3ae57f" }, 
        { "wheat", "#fbdd7e" }, 
        { "white", "#ffffff" }, 
        { "windows blue", "#3778bf" }, 
        { "wine red", "#7b0323" }, 
        { "wine", "#80013f" }, 
        { "wintergreen", "#20f986" }, 
        { "wisteria", "#a87dc2" }, 
        { "yellow brown", "#b79400" }, 
        { "yellow green", "#c0fb2d" }, 
        { "yellow ochre", "#cb9d06" }, 
        { "yellow orange", "#fcb001" }, 
        { "yellow tan", "#ffe36e" }, 
        { "yellow", "#ffff14" }, 
        { "yellow/green", "#c8fd3d" }, 
        { "yellowgreen", "#bbf90f" }, 
        { "yellowish brown", "#9b7a01" }, 
        { "yellowish green", "#b0dd16" }, 
        { "yellowish orange", "#ffab0f" }, 
        { "yellowish tan", "#fcfc81" }, 
        { "yellowish", "#faee66" }, 
        { "yellowy brown", "#ae8b0c" }, 
        { "yellowy green", "#bff128" }
    };
    
    private static readonly List<TestCaseData> HexTestData =
    [
        new TestCaseData("acid green", AcidGreen),
        new TestCaseData("adobe", Adobe),
        new TestCaseData("algae green", AlgaeGreen),
        new TestCaseData("algae", Algae),
        new TestCaseData("almost black", AlmostBlack),
        new TestCaseData("amber", Amber),
        new TestCaseData("amethyst", Amethyst),
        new TestCaseData("apple green", AppleGreen),
        new TestCaseData("apple", Apple),
        new TestCaseData("apricot", Apricot),
        new TestCaseData("aqua blue", AquaBlue),
        new TestCaseData("aqua green", AquaGreen),
        new TestCaseData("aqua marine", AquaMarine),
        new TestCaseData("aqua", Aqua),
        new TestCaseData("aquamarine", Aquamarine),
        new TestCaseData("army green", ArmyGreen),
        new TestCaseData("asparagus", Asparagus),
        new TestCaseData("aubergine", Aubergine),
        new TestCaseData("auburn", Auburn),
        new TestCaseData("avocado green", AvocadoGreen),
        new TestCaseData("avocado", Avocado),
        new TestCaseData("azul", Azul),
        new TestCaseData("azure", Azure),
        new TestCaseData("baby blue", BabyBlue),
        new TestCaseData("baby green", BabyGreen),
        new TestCaseData("baby pink", BabyPink),
        new TestCaseData("baby poo", BabyPoo),
        new TestCaseData("baby poop green", BabyPoopGreen),
        new TestCaseData("baby poop", BabyPoop),
        new TestCaseData("baby puke green", BabyPukeGreen),
        new TestCaseData("baby purple", BabyPurple),
        new TestCaseData("baby shit brown", BabyShitBrown),
        new TestCaseData("baby shit green", BabyShitGreen),
        new TestCaseData("banana yellow", BananaYellow),
        new TestCaseData("banana", Banana),
        new TestCaseData("barbie pink", BarbiePink),
        new TestCaseData("barf green", BarfGreen),
        new TestCaseData("barney purple", BarneyPurple),
        new TestCaseData("barney", Barney),
        new TestCaseData("battleship grey", BattleshipGrey),
        new TestCaseData("beige", Beige),
        new TestCaseData("berry", Berry),
        new TestCaseData("bile", Bile),
        new TestCaseData("black", Black),
        new TestCaseData("bland", Bland),
        new TestCaseData("blood orange", BloodOrange),
        new TestCaseData("blood red", BloodRed),
        new TestCaseData("blood", Blood),
        new TestCaseData("blue blue", BlueBlue),
        new TestCaseData("blue green", BlueGreen),
        new TestCaseData("blue grey", BlueGrey),
        new TestCaseData("blue purple", BluePurple),
        new TestCaseData("blue violet", BlueViolet),
        new TestCaseData("blue with a hint of purple", BlueWithAHintOfPurple),
        new TestCaseData("blue", Blue),
        new TestCaseData("blue/green", Blue_Green),
        new TestCaseData("blue/grey", Blue_Grey),
        new TestCaseData("blue/purple", Blue_Purple),
        new TestCaseData("blueberry", Blueberry),
        new TestCaseData("bluegreen", Bluegreen),
        new TestCaseData("bluegrey", Bluegrey),
        new TestCaseData("bluey green", BlueyGreen),
        new TestCaseData("bluey grey", BlueyGrey),
        new TestCaseData("bluey purple", BlueyPurple),
        new TestCaseData("bluish green", BluishGreen),
        new TestCaseData("bluish grey", BluishGrey),
        new TestCaseData("bluish purple", BluishPurple),
        new TestCaseData("bluish", Bluish),
        new TestCaseData("blurple", Blurple),
        new TestCaseData("blush pink", BlushPink),
        new TestCaseData("blush", Blush),
        new TestCaseData("booger green", BoogerGreen),
        new TestCaseData("booger", Booger),
        new TestCaseData("bordeaux", Bordeaux),
        new TestCaseData("boring green", BoringGreen),
        new TestCaseData("bottle green", BottleGreen),
        new TestCaseData("brick orange", BrickOrange),
        new TestCaseData("brick red", BrickRed),
        new TestCaseData("brick", Brick),
        new TestCaseData("bright aqua", BrightAqua),
        new TestCaseData("bright blue", BrightBlue),
        new TestCaseData("bright cyan", BrightCyan),
        new TestCaseData("bright green", BrightGreen),
        new TestCaseData("bright lavender", BrightLavender),
        new TestCaseData("bright light blue", BrightLightBlue),
        new TestCaseData("bright light green", BrightLightGreen),
        new TestCaseData("bright lilac", BrightLilac),
        new TestCaseData("bright lime green", BrightLimeGreen),
        new TestCaseData("bright lime", BrightLime),
        new TestCaseData("bright magenta", BrightMagenta),
        new TestCaseData("bright olive", BrightOlive),
        new TestCaseData("bright orange", BrightOrange),
        new TestCaseData("bright pink", BrightPink),
        new TestCaseData("bright purple", BrightPurple),
        new TestCaseData("bright red", BrightRed),
        new TestCaseData("bright sea green", BrightSeaGreen),
        new TestCaseData("bright sky blue", BrightSkyBlue),
        new TestCaseData("bright teal", BrightTeal),
        new TestCaseData("bright turquoise", BrightTurquoise),
        new TestCaseData("bright violet", BrightViolet),
        new TestCaseData("bright yellow green", BrightYellowGreen),
        new TestCaseData("bright yellow", BrightYellow),
        new TestCaseData("british racing green", BritishRacingGreen),
        new TestCaseData("bronze", Bronze),
        new TestCaseData("brown green", BrownGreen),
        new TestCaseData("brown grey", BrownGrey),
        new TestCaseData("brown orange", BrownOrange),
        new TestCaseData("brown red", BrownRed),
        new TestCaseData("brown yellow", BrownYellow),
        new TestCaseData("brown", Brown),
        new TestCaseData("brownish green", BrownishGreen),
        new TestCaseData("brownish grey", BrownishGrey),
        new TestCaseData("brownish orange", BrownishOrange),
        new TestCaseData("brownish pink", BrownishPink),
        new TestCaseData("brownish purple", BrownishPurple),
        new TestCaseData("brownish red", BrownishRed),
        new TestCaseData("brownish yellow", BrownishYellow),
        new TestCaseData("brownish", Brownish),
        new TestCaseData("browny green", BrownyGreen),
        new TestCaseData("browny orange", BrownyOrange),
        new TestCaseData("bruise", Bruise),
        new TestCaseData("bubble gum pink", BubbleGumPink),
        new TestCaseData("bubblegum pink", BubblegumPink),
        new TestCaseData("bubblegum", Bubblegum),
        new TestCaseData("buff", Buff),
        new TestCaseData("burgundy", Burgundy),
        new TestCaseData("burnt orange", BurntOrange),
        new TestCaseData("burnt red", BurntRed),
        new TestCaseData("burnt siena", BurntSiena),
        new TestCaseData("burnt sienna", BurntSienna),
        new TestCaseData("burnt umber", BurntUmber),
        new TestCaseData("burnt yellow", BurntYellow),
        new TestCaseData("burple", Burple),
        new TestCaseData("butter yellow", ButterYellow),
        new TestCaseData("butter", Butter),
        new TestCaseData("butterscotch", Butterscotch),
        new TestCaseData("cadet blue", CadetBlue),
        new TestCaseData("camel", Camel),
        new TestCaseData("camo green", CamoGreen),
        new TestCaseData("camo", Camo),
        new TestCaseData("camouflage green", CamouflageGreen),
        new TestCaseData("canary yellow", CanaryYellow),
        new TestCaseData("canary", Canary),
        new TestCaseData("candy pink", CandyPink),
        new TestCaseData("caramel", Caramel),
        new TestCaseData("carmine", Carmine),
        new TestCaseData("carnation pink", CarnationPink),
        new TestCaseData("carnation", Carnation),
        new TestCaseData("carolina blue", CarolinaBlue),
        new TestCaseData("celadon", Celadon),
        new TestCaseData("celery", Celery),
        new TestCaseData("cement", Cement),
        new TestCaseData("cerise", Cerise),
        new TestCaseData("cerulean blue", CeruleanBlue),
        new TestCaseData("cerulean", Cerulean),
        new TestCaseData("charcoal grey", CharcoalGrey),
        new TestCaseData("charcoal", Charcoal),
        new TestCaseData("chartreuse", Chartreuse),
        new TestCaseData("cherry red", CherryRed),
        new TestCaseData("cherry", Cherry),
        new TestCaseData("chestnut", Chestnut),
        new TestCaseData("chocolate brown", ChocolateBrown),
        new TestCaseData("chocolate", Chocolate),
        new TestCaseData("cinnamon", Cinnamon),
        new TestCaseData("claret", Claret),
        new TestCaseData("clay brown", ClayBrown),
        new TestCaseData("clay", Clay),
        new TestCaseData("clear blue", ClearBlue),
        new TestCaseData("cloudy blue", CloudyBlue),
        new TestCaseData("cobalt blue", CobaltBlue),
        new TestCaseData("cobalt", Cobalt),
        new TestCaseData("cocoa", Cocoa),
        new TestCaseData("coffee", Coffee),
        new TestCaseData("cool blue", CoolBlue),
        new TestCaseData("cool green", CoolGreen),
        new TestCaseData("cool grey", CoolGrey),
        new TestCaseData("copper", Copper),
        new TestCaseData("coral pink", CoralPink),
        new TestCaseData("coral", Coral),
        new TestCaseData("cornflower blue", CornflowerBlue),
        new TestCaseData("cornflower", Cornflower),
        new TestCaseData("cranberry", Cranberry),
        new TestCaseData("cream", Cream),
        new TestCaseData("creme", Creme),
        new TestCaseData("crimson", Crimson),
        new TestCaseData("custard", Custard),
        new TestCaseData("cyan", Cyan),
        new TestCaseData("dandelion", Dandelion),
        new TestCaseData("dark aqua", DarkAqua),
        new TestCaseData("dark aquamarine", DarkAquamarine),
        new TestCaseData("dark beige", DarkBeige),
        new TestCaseData("dark blue green", DarkBlueGreen),
        new TestCaseData("dark blue grey", DarkBlueGrey),
        new TestCaseData("dark blue", DarkBlue),
        new TestCaseData("dark brown", DarkBrown),
        new TestCaseData("dark coral", DarkCoral),
        new TestCaseData("dark cream", DarkCream),
        new TestCaseData("dark cyan", DarkCyan),
        new TestCaseData("dark forest green", DarkForestGreen),
        new TestCaseData("dark fuchsia", DarkFuchsia),
        new TestCaseData("dark gold", DarkGold),
        new TestCaseData("dark grass green", DarkGrassGreen),
        new TestCaseData("dark green blue", DarkGreenBlue),
        new TestCaseData("dark green", DarkGreen),
        new TestCaseData("dark grey blue", DarkGreyBlue),
        new TestCaseData("dark grey", DarkGrey),
        new TestCaseData("dark hot pink", DarkHotPink),
        new TestCaseData("dark indigo", DarkIndigo),
        new TestCaseData("dark khaki", DarkKhaki),
        new TestCaseData("dark lavender", DarkLavender),
        new TestCaseData("dark lilac", DarkLilac),
        new TestCaseData("dark lime green", DarkLimeGreen),
        new TestCaseData("dark lime", DarkLime),
        new TestCaseData("dark magenta", DarkMagenta),
        new TestCaseData("dark maroon", DarkMaroon),
        new TestCaseData("dark mauve", DarkMauve),
        new TestCaseData("dark mint green", DarkMintGreen),
        new TestCaseData("dark mint", DarkMint),
        new TestCaseData("dark mustard", DarkMustard),
        new TestCaseData("dark navy blue", DarkNavyBlue),
        new TestCaseData("dark navy", DarkNavy),
        new TestCaseData("dark olive green", DarkOliveGreen),
        new TestCaseData("dark olive", DarkOlive),
        new TestCaseData("dark orange", DarkOrange),
        new TestCaseData("dark pastel green", DarkPastelGreen),
        new TestCaseData("dark peach", DarkPeach),
        new TestCaseData("dark periwinkle", DarkPeriwinkle),
        new TestCaseData("dark pink", DarkPink),
        new TestCaseData("dark plum", DarkPlum),
        new TestCaseData("dark purple", DarkPurple),
        new TestCaseData("dark red", DarkRed),
        new TestCaseData("dark rose", DarkRose),
        new TestCaseData("dark royal blue", DarkRoyalBlue),
        new TestCaseData("dark sage", DarkSage),
        new TestCaseData("dark salmon", DarkSalmon),
        new TestCaseData("dark sand", DarkSand),
        new TestCaseData("dark sea green", DarkSeaGreen),
        new TestCaseData("dark seafoam green", DarkSeafoamGreen),
        new TestCaseData("dark seafoam", DarkSeafoam),
        new TestCaseData("dark sky blue", DarkSkyBlue),
        new TestCaseData("dark slate blue", DarkSlateBlue),
        new TestCaseData("dark tan", DarkTan),
        new TestCaseData("dark taupe", DarkTaupe),
        new TestCaseData("dark teal", DarkTeal),
        new TestCaseData("dark turquoise", DarkTurquoise),
        new TestCaseData("dark violet", DarkViolet),
        new TestCaseData("dark yellow green", DarkYellowGreen),
        new TestCaseData("dark yellow", DarkYellow),
        new TestCaseData("dark", Dark),
        new TestCaseData("darkblue", Darkblue),
        new TestCaseData("darkgreen", Darkgreen),
        new TestCaseData("darkish blue", DarkishBlue),
        new TestCaseData("darkish green", DarkishGreen),
        new TestCaseData("darkish pink", DarkishPink),
        new TestCaseData("darkish purple", DarkishPurple),
        new TestCaseData("darkish red", DarkishRed),
        new TestCaseData("deep aqua", DeepAqua),
        new TestCaseData("deep blue", DeepBlue),
        new TestCaseData("deep brown", DeepBrown),
        new TestCaseData("deep green", DeepGreen),
        new TestCaseData("deep lavender", DeepLavender),
        new TestCaseData("deep lilac", DeepLilac),
        new TestCaseData("deep magenta", DeepMagenta),
        new TestCaseData("deep orange", DeepOrange),
        new TestCaseData("deep pink", DeepPink),
        new TestCaseData("deep purple", DeepPurple),
        new TestCaseData("deep red", DeepRed),
        new TestCaseData("deep rose", DeepRose),
        new TestCaseData("deep sea blue", DeepSeaBlue),
        new TestCaseData("deep sky blue", DeepSkyBlue),
        new TestCaseData("deep teal", DeepTeal),
        new TestCaseData("deep turquoise", DeepTurquoise),
        new TestCaseData("deep violet", DeepViolet),
        new TestCaseData("denim blue", DenimBlue),
        new TestCaseData("denim", Denim),
        new TestCaseData("desert", Desert),
        new TestCaseData("diarrhea", Diarrhea),
        new TestCaseData("dirt brown", DirtBrown),
        new TestCaseData("dirt", Dirt),
        new TestCaseData("dirty blue", DirtyBlue),
        new TestCaseData("dirty green", DirtyGreen),
        new TestCaseData("dirty orange", DirtyOrange),
        new TestCaseData("dirty pink", DirtyPink),
        new TestCaseData("dirty purple", DirtyPurple),
        new TestCaseData("dirty yellow", DirtyYellow),
        new TestCaseData("dodger blue", DodgerBlue),
        new TestCaseData("drab green", DrabGreen),
        new TestCaseData("drab", Drab),
        new TestCaseData("dried blood", DriedBlood),
        new TestCaseData("duck egg blue", DuckEggBlue),
        new TestCaseData("dull blue", DullBlue),
        new TestCaseData("dull brown", DullBrown),
        new TestCaseData("dull green", DullGreen),
        new TestCaseData("dull orange", DullOrange),
        new TestCaseData("dull pink", DullPink),
        new TestCaseData("dull purple", DullPurple),
        new TestCaseData("dull red", DullRed),
        new TestCaseData("dull teal", DullTeal),
        new TestCaseData("dull yellow", DullYellow),
        new TestCaseData("dusk blue", DuskBlue),
        new TestCaseData("dusk", Dusk),
        new TestCaseData("dusky blue", DuskyBlue),
        new TestCaseData("dusky pink", DuskyPink),
        new TestCaseData("dusky purple", DuskyPurple),
        new TestCaseData("dusky rose", DuskyRose),
        new TestCaseData("dust", Dust),
        new TestCaseData("dusty blue", DustyBlue),
        new TestCaseData("dusty green", DustyGreen),
        new TestCaseData("dusty lavender", DustyLavender),
        new TestCaseData("dusty orange", DustyOrange),
        new TestCaseData("dusty pink", DustyPink),
        new TestCaseData("dusty purple", DustyPurple),
        new TestCaseData("dusty red", DustyRed),
        new TestCaseData("dusty rose", DustyRose),
        new TestCaseData("dusty teal", DustyTeal),
        new TestCaseData("earth", Earth),
        new TestCaseData("easter green", EasterGreen),
        new TestCaseData("easter purple", EasterPurple),
        new TestCaseData("ecru", Ecru),
        new TestCaseData("egg shell", EggShell),
        new TestCaseData("eggplant purple", EggplantPurple),
        new TestCaseData("eggplant", Eggplant),
        new TestCaseData("eggshell blue", EggshellBlue),
        new TestCaseData("eggshell", Eggshell),
        new TestCaseData("electric blue", ElectricBlue),
        new TestCaseData("electric green", ElectricGreen),
        new TestCaseData("electric lime", ElectricLime),
        new TestCaseData("electric pink", ElectricPink),
        new TestCaseData("electric purple", ElectricPurple),
        new TestCaseData("emerald green", EmeraldGreen),
        new TestCaseData("emerald", Emerald),
        new TestCaseData("evergreen", Evergreen),
        new TestCaseData("faded blue", FadedBlue),
        new TestCaseData("faded green", FadedGreen),
        new TestCaseData("faded orange", FadedOrange),
        new TestCaseData("faded pink", FadedPink),
        new TestCaseData("faded purple", FadedPurple),
        new TestCaseData("faded red", FadedRed),
        new TestCaseData("faded yellow", FadedYellow),
        new TestCaseData("fawn", Fawn),
        new TestCaseData("fern green", FernGreen),
        new TestCaseData("fern", Fern),
        new TestCaseData("fire engine red", FireEngineRed),
        new TestCaseData("flat blue", FlatBlue),
        new TestCaseData("flat green", FlatGreen),
        new TestCaseData("fluorescent green", FluorescentGreen),
        new TestCaseData("fluro green", FluroGreen),
        new TestCaseData("foam green", FoamGreen),
        new TestCaseData("forest green", ForestGreen),
        new TestCaseData("forest", Forest),
        new TestCaseData("forrest green", ForrestGreen),
        new TestCaseData("french blue", FrenchBlue),
        new TestCaseData("fresh green", FreshGreen),
        new TestCaseData("frog green", FrogGreen),
        new TestCaseData("fuchsia", Fuchsia),
        new TestCaseData("gold", Gold),
        new TestCaseData("golden brown", GoldenBrown),
        new TestCaseData("golden rod", GoldenRod),
        new TestCaseData("golden yellow", GoldenYellow),
        new TestCaseData("golden", Golden),
        new TestCaseData("goldenrod", Goldenrod),
        new TestCaseData("grape purple", GrapePurple),
        new TestCaseData("grape", Grape),
        new TestCaseData("grapefruit", Grapefruit),
        new TestCaseData("grass green", GrassGreen),
        new TestCaseData("grass", Grass),
        new TestCaseData("grassy green", GrassyGreen),
        new TestCaseData("green apple", GreenApple),
        new TestCaseData("green blue", GreenBlue),
        new TestCaseData("green brown", GreenBrown),
        new TestCaseData("green grey", GreenGrey),
        new TestCaseData("green teal", GreenTeal),
        new TestCaseData("green yellow", GreenYellow),
        new TestCaseData("green", Green),
        new TestCaseData("green/blue", Green_Blue),
        new TestCaseData("green/yellow", Green_Yellow),
        new TestCaseData("greenblue", Greenblue),
        new TestCaseData("greenish beige", GreenishBeige),
        new TestCaseData("greenish blue", GreenishBlue),
        new TestCaseData("greenish brown", GreenishBrown),
        new TestCaseData("greenish cyan", GreenishCyan),
        new TestCaseData("greenish grey", GreenishGrey),
        new TestCaseData("greenish tan", GreenishTan),
        new TestCaseData("greenish teal", GreenishTeal),
        new TestCaseData("greenish turquoise", GreenishTurquoise),
        new TestCaseData("greenish yellow", GreenishYellow),
        new TestCaseData("greenish", Greenish),
        new TestCaseData("greeny blue", GreenyBlue),
        new TestCaseData("greeny brown", GreenyBrown),
        new TestCaseData("greeny grey", GreenyGrey),
        new TestCaseData("greeny yellow", GreenyYellow),
        new TestCaseData("grey blue", GreyBlue),
        new TestCaseData("grey brown", GreyBrown),
        new TestCaseData("grey green", GreyGreen),
        new TestCaseData("grey pink", GreyPink),
        new TestCaseData("grey purple", GreyPurple),
        new TestCaseData("grey teal", GreyTeal),
        new TestCaseData("grey", Grey),
        new TestCaseData("grey/blue", Grey_Blue),
        new TestCaseData("grey/green", Grey_Green),
        new TestCaseData("greyblue", Greyblue),
        new TestCaseData("greyish blue", GreyishBlue),
        new TestCaseData("greyish brown", GreyishBrown),
        new TestCaseData("greyish green", GreyishGreen),
        new TestCaseData("greyish pink", GreyishPink),
        new TestCaseData("greyish purple", GreyishPurple),
        new TestCaseData("greyish teal", GreyishTeal),
        new TestCaseData("greyish", Greyish),
        new TestCaseData("gross green", GrossGreen),
        new TestCaseData("gunmetal", Gunmetal),
        new TestCaseData("hazel", Hazel),
        new TestCaseData("heather", Heather),
        new TestCaseData("heliotrope", Heliotrope),
        new TestCaseData("highlighter green", HighlighterGreen),
        new TestCaseData("hospital green", HospitalGreen),
        new TestCaseData("hot green", HotGreen),
        new TestCaseData("hot magenta", HotMagenta),
        new TestCaseData("hot pink", HotPink),
        new TestCaseData("hot purple", HotPurple),
        new TestCaseData("hunter green", HunterGreen),
        new TestCaseData("ice blue", IceBlue),
        new TestCaseData("ice", Ice),
        new TestCaseData("icky green", IckyGreen),
        new TestCaseData("indian red", IndianRed),
        new TestCaseData("indigo blue", IndigoBlue),
        new TestCaseData("indigo", Indigo),
        new TestCaseData("iris", Iris),
        new TestCaseData("irish green", IrishGreen),
        new TestCaseData("ivory", Ivory),
        new TestCaseData("jade green", JadeGreen),
        new TestCaseData("jade", Jade),
        new TestCaseData("jungle green", JungleGreen),
        new TestCaseData("kelley green", KelleyGreen),
        new TestCaseData("kelly green", KellyGreen),
        new TestCaseData("kermit green", KermitGreen),
        new TestCaseData("key lime", KeyLime),
        new TestCaseData("khaki green", KhakiGreen),
        new TestCaseData("khaki", Khaki),
        new TestCaseData("kiwi green", KiwiGreen),
        new TestCaseData("kiwi", Kiwi),
        new TestCaseData("lavender blue", LavenderBlue),
        new TestCaseData("lavender pink", LavenderPink),
        new TestCaseData("lavender", Lavender),
        new TestCaseData("lawn green", LawnGreen),
        new TestCaseData("leaf green", LeafGreen),
        new TestCaseData("leaf", Leaf),
        new TestCaseData("leafy green", LeafyGreen),
        new TestCaseData("leather", Leather),
        new TestCaseData("lemon green", LemonGreen),
        new TestCaseData("lemon lime", LemonLime),
        new TestCaseData("lemon yellow", LemonYellow),
        new TestCaseData("lemon", Lemon),
        new TestCaseData("lichen", Lichen),
        new TestCaseData("light aqua", LightAqua),
        new TestCaseData("light aquamarine", LightAquamarine),
        new TestCaseData("light beige", LightBeige),
        new TestCaseData("light blue green", LightBlueGreen),
        new TestCaseData("light blue grey", LightBlueGrey),
        new TestCaseData("light blue", LightBlue),
        new TestCaseData("light bluish green", LightBluishGreen),
        new TestCaseData("light bright green", LightBrightGreen),
        new TestCaseData("light brown", LightBrown),
        new TestCaseData("light burgundy", LightBurgundy),
        new TestCaseData("light cyan", LightCyan),
        new TestCaseData("light eggplant", LightEggplant),
        new TestCaseData("light forest green", LightForestGreen),
        new TestCaseData("light gold", LightGold),
        new TestCaseData("light grass green", LightGrassGreen),
        new TestCaseData("light green blue", LightGreenBlue),
        new TestCaseData("light green", LightGreen),
        new TestCaseData("light greenish blue", LightGreenishBlue),
        new TestCaseData("light grey blue", LightGreyBlue),
        new TestCaseData("light grey green", LightGreyGreen),
        new TestCaseData("light grey", LightGrey),
        new TestCaseData("light indigo", LightIndigo),
        new TestCaseData("light khaki", LightKhaki),
        new TestCaseData("light lavendar", LightLavendar),
        new TestCaseData("light lavender", LightLavender),
        new TestCaseData("light light blue", LightLightBlue),
        new TestCaseData("light light green", LightLightGreen),
        new TestCaseData("light lilac", LightLilac),
        new TestCaseData("light lime green", LightLimeGreen),
        new TestCaseData("light lime", LightLime),
        new TestCaseData("light magenta", LightMagenta),
        new TestCaseData("light maroon", LightMaroon),
        new TestCaseData("light mauve", LightMauve),
        new TestCaseData("light mint green", LightMintGreen),
        new TestCaseData("light mint", LightMint),
        new TestCaseData("light moss green", LightMossGreen),
        new TestCaseData("light mustard", LightMustard),
        new TestCaseData("light navy blue", LightNavyBlue),
        new TestCaseData("light navy", LightNavy),
        new TestCaseData("light neon green", LightNeonGreen),
        new TestCaseData("light olive green", LightOliveGreen),
        new TestCaseData("light olive", LightOlive),
        new TestCaseData("light orange", LightOrange),
        new TestCaseData("light pastel green", LightPastelGreen),
        new TestCaseData("light pea green", LightPeaGreen),
        new TestCaseData("light peach", LightPeach),
        new TestCaseData("light periwinkle", LightPeriwinkle),
        new TestCaseData("light pink", LightPink),
        new TestCaseData("light plum", LightPlum),
        new TestCaseData("light purple", LightPurple),
        new TestCaseData("light red", LightRed),
        new TestCaseData("light rose", LightRose),
        new TestCaseData("light royal blue", LightRoyalBlue),
        new TestCaseData("light sage", LightSage),
        new TestCaseData("light salmon", LightSalmon),
        new TestCaseData("light sea green", LightSeaGreen),
        new TestCaseData("light seafoam green", LightSeafoamGreen),
        new TestCaseData("light seafoam", LightSeafoam),
        new TestCaseData("light sky blue", LightSkyBlue),
        new TestCaseData("light tan", LightTan),
        new TestCaseData("light teal", LightTeal),
        new TestCaseData("light turquoise", LightTurquoise),
        new TestCaseData("light urple", LightUrple),
        new TestCaseData("light violet", LightViolet),
        new TestCaseData("light yellow green", LightYellowGreen),
        new TestCaseData("light yellow", LightYellow),
        new TestCaseData("light yellowish green", LightYellowishGreen),
        new TestCaseData("lightblue", Lightblue),
        new TestCaseData("lighter green", LighterGreen),
        new TestCaseData("lighter purple", LighterPurple),
        new TestCaseData("lightgreen", Lightgreen),
        new TestCaseData("lightish blue", LightishBlue),
        new TestCaseData("lightish green", LightishGreen),
        new TestCaseData("lightish purple", LightishPurple),
        new TestCaseData("lightish red", LightishRed),
        new TestCaseData("lilac", Lilac),
        new TestCaseData("liliac", Liliac),
        new TestCaseData("lime green", LimeGreen),
        new TestCaseData("lime yellow", LimeYellow),
        new TestCaseData("lime", Lime),
        new TestCaseData("lipstick red", LipstickRed),
        new TestCaseData("lipstick", Lipstick),
        new TestCaseData("macaroni and cheese", MacaroniAndCheese),
        new TestCaseData("magenta", Magenta),
        new TestCaseData("mahogany", Mahogany),
        new TestCaseData("maize", Maize),
        new TestCaseData("mango", Mango),
        new TestCaseData("manilla", Manilla),
        new TestCaseData("marigold", Marigold),
        new TestCaseData("marine blue", MarineBlue),
        new TestCaseData("marine", Marine),
        new TestCaseData("maroon", Maroon),
        new TestCaseData("mauve", Mauve),
        new TestCaseData("medium blue", MediumBlue),
        new TestCaseData("medium brown", MediumBrown),
        new TestCaseData("medium green", MediumGreen),
        new TestCaseData("medium grey", MediumGrey),
        new TestCaseData("medium pink", MediumPink),
        new TestCaseData("medium purple", MediumPurple),
        new TestCaseData("melon", Melon),
        new TestCaseData("merlot", Merlot),
        new TestCaseData("metallic blue", MetallicBlue),
        new TestCaseData("mid blue", MidBlue),
        new TestCaseData("mid green", MidGreen),
        new TestCaseData("midnight blue", MidnightBlue),
        new TestCaseData("midnight purple", MidnightPurple),
        new TestCaseData("midnight", Midnight),
        new TestCaseData("military green", MilitaryGreen),
        new TestCaseData("milk chocolate", MilkChocolate),
        new TestCaseData("mint green", MintGreen),
        new TestCaseData("mint", Mint),
        new TestCaseData("minty green", MintyGreen),
        new TestCaseData("mocha", Mocha),
        new TestCaseData("moss green", MossGreen),
        new TestCaseData("moss", Moss),
        new TestCaseData("mossy green", MossyGreen),
        new TestCaseData("mud brown", MudBrown),
        new TestCaseData("mud green", MudGreen),
        new TestCaseData("mud", Mud),
        new TestCaseData("muddy brown", MuddyBrown),
        new TestCaseData("muddy green", MuddyGreen),
        new TestCaseData("muddy yellow", MuddyYellow),
        new TestCaseData("mulberry", Mulberry),
        new TestCaseData("murky green", MurkyGreen),
        new TestCaseData("mushroom", Mushroom),
        new TestCaseData("mustard brown", MustardBrown),
        new TestCaseData("mustard green", MustardGreen),
        new TestCaseData("mustard yellow", MustardYellow),
        new TestCaseData("mustard", Mustard),
        new TestCaseData("muted blue", MutedBlue),
        new TestCaseData("muted green", MutedGreen),
        new TestCaseData("muted pink", MutedPink),
        new TestCaseData("muted purple", MutedPurple),
        new TestCaseData("nasty green", NastyGreen),
        new TestCaseData("navy blue", NavyBlue),
        new TestCaseData("navy green", NavyGreen),
        new TestCaseData("navy", Navy),
        new TestCaseData("neon blue", NeonBlue),
        new TestCaseData("neon green", NeonGreen),
        new TestCaseData("neon pink", NeonPink),
        new TestCaseData("neon purple", NeonPurple),
        new TestCaseData("neon red", NeonRed),
        new TestCaseData("neon yellow", NeonYellow),
        new TestCaseData("nice blue", NiceBlue),
        new TestCaseData("night blue", NightBlue),
        new TestCaseData("ocean blue", OceanBlue),
        new TestCaseData("ocean green", OceanGreen),
        new TestCaseData("ocean", Ocean),
        new TestCaseData("ocher", Ocher),
        new TestCaseData("ochre", Ochre),
        new TestCaseData("ocre", Ocre),
        new TestCaseData("off blue", OffBlue),
        new TestCaseData("off green", OffGreen),
        new TestCaseData("off white", OffWhite),
        new TestCaseData("off yellow", OffYellow),
        new TestCaseData("old pink", OldPink),
        new TestCaseData("old rose", OldRose),
        new TestCaseData("olive brown", OliveBrown),
        new TestCaseData("olive drab", OliveDrab),
        new TestCaseData("olive green", OliveGreen),
        new TestCaseData("olive yellow", OliveYellow),
        new TestCaseData("olive", Olive),
        new TestCaseData("orange brown", OrangeBrown),
        new TestCaseData("orange pink", OrangePink),
        new TestCaseData("orange red", OrangeRed),
        new TestCaseData("orange yellow", OrangeYellow),
        new TestCaseData("orange", Orange),
        new TestCaseData("orangeish", Orangeish),
        new TestCaseData("orangered", Orangered),
        new TestCaseData("orangey brown", OrangeyBrown),
        new TestCaseData("orangey red", OrangeyRed),
        new TestCaseData("orangey yellow", OrangeyYellow),
        new TestCaseData("orangish brown", OrangishBrown),
        new TestCaseData("orangish red", OrangishRed),
        new TestCaseData("orangish", Orangish),
        new TestCaseData("orchid", Orchid),
        new TestCaseData("pale aqua", PaleAqua),
        new TestCaseData("pale blue", PaleBlue),
        new TestCaseData("pale brown", PaleBrown),
        new TestCaseData("pale cyan", PaleCyan),
        new TestCaseData("pale gold", PaleGold),
        new TestCaseData("pale green", PaleGreen),
        new TestCaseData("pale grey", PaleGrey),
        new TestCaseData("pale lavender", PaleLavender),
        new TestCaseData("pale light green", PaleLightGreen),
        new TestCaseData("pale lilac", PaleLilac),
        new TestCaseData("pale lime green", PaleLimeGreen),
        new TestCaseData("pale lime", PaleLime),
        new TestCaseData("pale magenta", PaleMagenta),
        new TestCaseData("pale mauve", PaleMauve),
        new TestCaseData("pale olive green", PaleOliveGreen),
        new TestCaseData("pale olive", PaleOlive),
        new TestCaseData("pale orange", PaleOrange),
        new TestCaseData("pale peach", PalePeach),
        new TestCaseData("pale pink", PalePink),
        new TestCaseData("pale purple", PalePurple),
        new TestCaseData("pale red", PaleRed),
        new TestCaseData("pale rose", PaleRose),
        new TestCaseData("pale salmon", PaleSalmon),
        new TestCaseData("pale sky blue", PaleSkyBlue),
        new TestCaseData("pale teal", PaleTeal),
        new TestCaseData("pale turquoise", PaleTurquoise),
        new TestCaseData("pale violet", PaleViolet),
        new TestCaseData("pale yellow", PaleYellow),
        new TestCaseData("pale", Pale),
        new TestCaseData("parchment", Parchment),
        new TestCaseData("pastel blue", PastelBlue),
        new TestCaseData("pastel green", PastelGreen),
        new TestCaseData("pastel orange", PastelOrange),
        new TestCaseData("pastel pink", PastelPink),
        new TestCaseData("pastel purple", PastelPurple),
        new TestCaseData("pastel red", PastelRed),
        new TestCaseData("pastel yellow", PastelYellow),
        new TestCaseData("pea green", PeaGreen),
        new TestCaseData("pea soup green", PeaSoupGreen),
        new TestCaseData("pea soup", PeaSoup),
        new TestCaseData("pea", Pea),
        new TestCaseData("peach", Peach),
        new TestCaseData("peachy pink", PeachyPink),
        new TestCaseData("peacock blue", PeacockBlue),
        new TestCaseData("pear", Pear),
        new TestCaseData("periwinkle blue", PeriwinkleBlue),
        new TestCaseData("periwinkle", Periwinkle),
        new TestCaseData("perrywinkle", Perrywinkle),
        new TestCaseData("petrol", Petrol),
        new TestCaseData("pig pink", PigPink),
        new TestCaseData("pine green", PineGreen),
        new TestCaseData("pine", Pine),
        new TestCaseData("pink purple", PinkPurple),
        new TestCaseData("pink red", PinkRed),
        new TestCaseData("pink", Pink),
        new TestCaseData("pink/purple", Pink_Purple),
        new TestCaseData("pinkish brown", PinkishBrown),
        new TestCaseData("pinkish grey", PinkishGrey),
        new TestCaseData("pinkish orange", PinkishOrange),
        new TestCaseData("pinkish purple", PinkishPurple),
        new TestCaseData("pinkish red", PinkishRed),
        new TestCaseData("pinkish tan", PinkishTan),
        new TestCaseData("pinkish", Pinkish),
        new TestCaseData("pinky purple", PinkyPurple),
        new TestCaseData("pinky red", PinkyRed),
        new TestCaseData("pinky", Pinky),
        new TestCaseData("piss yellow", PissYellow),
        new TestCaseData("pistachio", Pistachio),
        new TestCaseData("plum purple", PlumPurple),
        new TestCaseData("plum", Plum),
        new TestCaseData("poison green", PoisonGreen),
        new TestCaseData("poo brown", PooBrown),
        new TestCaseData("poo", Poo),
        new TestCaseData("poop brown", PoopBrown),
        new TestCaseData("poop green", PoopGreen),
        new TestCaseData("poop", Poop),
        new TestCaseData("powder blue", PowderBlue),
        new TestCaseData("powder pink", PowderPink),
        new TestCaseData("primary blue", PrimaryBlue),
        new TestCaseData("prussian blue", PrussianBlue),
        new TestCaseData("puce", Puce),
        new TestCaseData("puke brown", PukeBrown),
        new TestCaseData("puke green", PukeGreen),
        new TestCaseData("puke yellow", PukeYellow),
        new TestCaseData("puke", Puke),
        new TestCaseData("pumpkin orange", PumpkinOrange),
        new TestCaseData("pumpkin", Pumpkin),
        new TestCaseData("pure blue", PureBlue),
        new TestCaseData("purple blue", PurpleBlue),
        new TestCaseData("purple brown", PurpleBrown),
        new TestCaseData("purple grey", PurpleGrey),
        new TestCaseData("purple pink", PurplePink),
        new TestCaseData("purple red", PurpleRed),
        new TestCaseData("purple", Purple),
        new TestCaseData("purple/blue", Purple_Blue),
        new TestCaseData("purple/pink", Purple_Pink),
        new TestCaseData("purpleish blue", PurpleishBlue),
        new TestCaseData("purpleish pink", PurpleishPink),
        new TestCaseData("purpleish", Purpleish),
        new TestCaseData("purpley blue", PurpleyBlue),
        new TestCaseData("purpley grey", PurpleyGrey),
        new TestCaseData("purpley pink", PurpleyPink),
        new TestCaseData("purpley", Purpley),
        new TestCaseData("purplish blue", PurplishBlue),
        new TestCaseData("purplish brown", PurplishBrown),
        new TestCaseData("purplish grey", PurplishGrey),
        new TestCaseData("purplish pink", PurplishPink),
        new TestCaseData("purplish red", PurplishRed),
        new TestCaseData("purplish", Purplish),
        new TestCaseData("purply blue", PurplyBlue),
        new TestCaseData("purply pink", PurplyPink),
        new TestCaseData("purply", Purply),
        new TestCaseData("putty", Putty),
        new TestCaseData("racing green", RacingGreen),
        new TestCaseData("radioactive green", RadioactiveGreen),
        new TestCaseData("raspberry", Raspberry),
        new TestCaseData("raw sienna", RawSienna),
        new TestCaseData("raw umber", RawUmber),
        new TestCaseData("really light blue", ReallyLightBlue),
        new TestCaseData("red brown", RedBrown),
        new TestCaseData("red orange", RedOrange),
        new TestCaseData("red pink", RedPink),
        new TestCaseData("red purple", RedPurple),
        new TestCaseData("red violet", RedViolet),
        new TestCaseData("red wine", RedWine),
        new TestCaseData("red", Red),
        new TestCaseData("reddish brown", ReddishBrown),
        new TestCaseData("reddish grey", ReddishGrey),
        new TestCaseData("reddish orange", ReddishOrange),
        new TestCaseData("reddish pink", ReddishPink),
        new TestCaseData("reddish purple", ReddishPurple),
        new TestCaseData("reddish", Reddish),
        new TestCaseData("reddy brown", ReddyBrown),
        new TestCaseData("rich blue", RichBlue),
        new TestCaseData("rich purple", RichPurple),
        new TestCaseData("robin egg blue", RobinEggBlue),
        new TestCaseData("robin's egg blue", RobinsEggBlue),
        new TestCaseData("robin's egg", RobinsEgg),
        new TestCaseData("rosa", Rosa),
        new TestCaseData("rose pink", RosePink),
        new TestCaseData("rose red", RoseRed),
        new TestCaseData("rose", Rose),
        new TestCaseData("rosy pink", RosyPink),
        new TestCaseData("rouge", Rouge),
        new TestCaseData("royal blue", RoyalBlue),
        new TestCaseData("royal purple", RoyalPurple),
        new TestCaseData("royal", Royal),
        new TestCaseData("ruby", Ruby),
        new TestCaseData("russet", Russet),
        new TestCaseData("rust brown", RustBrown),
        new TestCaseData("rust orange", RustOrange),
        new TestCaseData("rust red", RustRed),
        new TestCaseData("rust", Rust),
        new TestCaseData("rusty orange", RustyOrange),
        new TestCaseData("rusty red", RustyRed),
        new TestCaseData("saffron", Saffron),
        new TestCaseData("sage green", SageGreen),
        new TestCaseData("sage", Sage),
        new TestCaseData("salmon pink", SalmonPink),
        new TestCaseData("salmon", Salmon),
        new TestCaseData("sand brown", SandBrown),
        new TestCaseData("sand yellow", SandYellow),
        new TestCaseData("sand", Sand),
        new TestCaseData("sandstone", Sandstone),
        new TestCaseData("sandy brown", SandyBrown),
        new TestCaseData("sandy yellow", SandyYellow),
        new TestCaseData("sandy", Sandy),
        new TestCaseData("sap green", SapGreen),
        new TestCaseData("sapphire", Sapphire),
        new TestCaseData("scarlet", Scarlet),
        new TestCaseData("sea blue", SeaBlue),
        new TestCaseData("sea green", SeaGreen),
        new TestCaseData("sea", Sea),
        new TestCaseData("seafoam blue", SeafoamBlue),
        new TestCaseData("seafoam green", SeafoamGreen),
        new TestCaseData("seafoam", Seafoam),
        new TestCaseData("seaweed green", SeaweedGreen),
        new TestCaseData("seaweed", Seaweed),
        new TestCaseData("sepia", Sepia),
        new TestCaseData("shamrock green", ShamrockGreen),
        new TestCaseData("shamrock", Shamrock),
        new TestCaseData("shit brown", ShitBrown),
        new TestCaseData("shit green", ShitGreen),
        new TestCaseData("shit", Shit),
        new TestCaseData("shocking pink", ShockingPink),
        new TestCaseData("sick green", SickGreen),
        new TestCaseData("sickly green", SicklyGreen),
        new TestCaseData("sickly yellow", SicklyYellow),
        new TestCaseData("sienna", Sienna),
        new TestCaseData("silver", Silver),
        new TestCaseData("sky blue", SkyBlue),
        new TestCaseData("sky", Sky),
        new TestCaseData("slate blue", SlateBlue),
        new TestCaseData("slate green", SlateGreen),
        new TestCaseData("slate grey", SlateGrey),
        new TestCaseData("slate", Slate),
        new TestCaseData("slime green", SlimeGreen),
        new TestCaseData("snot green", SnotGreen),
        new TestCaseData("snot", Snot),
        new TestCaseData("soft blue", SoftBlue),
        new TestCaseData("soft green", SoftGreen),
        new TestCaseData("soft pink", SoftPink),
        new TestCaseData("soft purple", SoftPurple),
        new TestCaseData("spearmint", Spearmint),
        new TestCaseData("spring green", SpringGreen),
        new TestCaseData("spruce", Spruce),
        new TestCaseData("squash", Squash),
        new TestCaseData("steel blue", SteelBlue),
        new TestCaseData("steel grey", SteelGrey),
        new TestCaseData("steel", Steel),
        new TestCaseData("stone", Stone),
        new TestCaseData("stormy blue", StormyBlue),
        new TestCaseData("straw", Straw),
        new TestCaseData("strawberry", Strawberry),
        new TestCaseData("strong blue", StrongBlue),
        new TestCaseData("strong pink", StrongPink),
        new TestCaseData("sun yellow", SunYellow),
        new TestCaseData("sunflower yellow", SunflowerYellow),
        new TestCaseData("sunflower", Sunflower),
        new TestCaseData("sunny yellow", SunnyYellow),
        new TestCaseData("sunshine yellow", SunshineYellow),
        new TestCaseData("swamp green", SwampGreen),
        new TestCaseData("swamp", Swamp),
        new TestCaseData("tan brown", TanBrown),
        new TestCaseData("tan green", TanGreen),
        new TestCaseData("tan", Tan),
        new TestCaseData("tangerine", Tangerine),
        new TestCaseData("taupe", Taupe),
        new TestCaseData("tea green", TeaGreen),
        new TestCaseData("tea", Tea),
        new TestCaseData("teal blue", TealBlue),
        new TestCaseData("teal green", TealGreen),
        new TestCaseData("teal", Teal),
        new TestCaseData("tealish green", TealishGreen),
        new TestCaseData("tealish", Tealish),
        new TestCaseData("terra cotta", TerraCotta),
        new TestCaseData("terracota", Terracota),
        new TestCaseData("terracotta", Terracotta),
        new TestCaseData("tiffany blue", TiffanyBlue),
        new TestCaseData("tomato red", TomatoRed),
        new TestCaseData("tomato", Tomato),
        new TestCaseData("topaz", Topaz),
        new TestCaseData("toupe", Toupe),
        new TestCaseData("toxic green", ToxicGreen),
        new TestCaseData("tree green", TreeGreen),
        new TestCaseData("true blue", TrueBlue),
        new TestCaseData("true green", TrueGreen),
        new TestCaseData("turquoise blue", TurquoiseBlue),
        new TestCaseData("turquoise green", TurquoiseGreen),
        new TestCaseData("turquoise", Turquoise),
        new TestCaseData("turtle green", TurtleGreen),
        new TestCaseData("twilight blue", TwilightBlue),
        new TestCaseData("twilight", Xkcd.Twilight),
        new TestCaseData("ugly blue", UglyBlue),
        new TestCaseData("ugly brown", UglyBrown),
        new TestCaseData("ugly green", UglyGreen),
        new TestCaseData("ugly pink", UglyPink),
        new TestCaseData("ugly purple", UglyPurple),
        new TestCaseData("ugly yellow", UglyYellow),
        new TestCaseData("ultramarine blue", UltramarineBlue),
        new TestCaseData("ultramarine", Ultramarine),
        new TestCaseData("umber", Umber),
        new TestCaseData("velvet", Velvet),
        new TestCaseData("vermillion", Vermillion),
        new TestCaseData("very dark blue", VeryDarkBlue),
        new TestCaseData("very dark brown", VeryDarkBrown),
        new TestCaseData("very dark green", VeryDarkGreen),
        new TestCaseData("very dark purple", VeryDarkPurple),
        new TestCaseData("very light blue", VeryLightBlue),
        new TestCaseData("very light brown", VeryLightBrown),
        new TestCaseData("very light green", VeryLightGreen),
        new TestCaseData("very light pink", VeryLightPink),
        new TestCaseData("very light purple", VeryLightPurple),
        new TestCaseData("very pale blue", VeryPaleBlue),
        new TestCaseData("very pale green", VeryPaleGreen),
        new TestCaseData("vibrant blue", VibrantBlue),
        new TestCaseData("vibrant green", VibrantGreen),
        new TestCaseData("vibrant purple", VibrantPurple),
        new TestCaseData("violet blue", VioletBlue),
        new TestCaseData("violet pink", VioletPink),
        new TestCaseData("violet red", VioletRed),
        new TestCaseData("violet", Violet),
        new TestCaseData("viridian", Viridian),
        new TestCaseData("vivid blue", VividBlue),
        new TestCaseData("vivid green", VividGreen),
        new TestCaseData("vivid purple", VividPurple),
        new TestCaseData("vomit green", VomitGreen),
        new TestCaseData("vomit yellow", VomitYellow),
        new TestCaseData("vomit", Vomit),
        new TestCaseData("warm blue", WarmBlue),
        new TestCaseData("warm brown", WarmBrown),
        new TestCaseData("warm grey", WarmGrey),
        new TestCaseData("warm pink", WarmPink),
        new TestCaseData("warm purple", WarmPurple),
        new TestCaseData("washed out green", WashedOutGreen),
        new TestCaseData("water blue", WaterBlue),
        new TestCaseData("watermelon", Watermelon),
        new TestCaseData("weird green", WeirdGreen),
        new TestCaseData("wheat", Wheat),
        new TestCaseData("white", White),
        new TestCaseData("windows blue", WindowsBlue),
        new TestCaseData("wine red", WineRed),
        new TestCaseData("wine", Wine),
        new TestCaseData("wintergreen", Wintergreen),
        new TestCaseData("wisteria", Wisteria),
        new TestCaseData("yellow brown", YellowBrown),
        new TestCaseData("yellow green", YellowGreen),
        new TestCaseData("yellow ochre", YellowOchre),
        new TestCaseData("yellow orange", YellowOrange),
        new TestCaseData("yellow tan", YellowTan),
        new TestCaseData("yellow", Yellow),
        new TestCaseData("yellow/green", Yellow_Green),
        new TestCaseData("yellowgreen", Yellowgreen),
        new TestCaseData("yellowish brown", YellowishBrown),
        new TestCaseData("yellowish green", YellowishGreen),
        new TestCaseData("yellowish orange", YellowishOrange),
        new TestCaseData("yellowish tan", YellowishTan),
        new TestCaseData("yellowish", Yellowish),
        new TestCaseData("yellowy brown", YellowyBrown),
        new TestCaseData("yellowy green", YellowyGreen)
    ];

    [TestCaseSource(nameof(HexTestData))]
    public void Hex(string name, Unicolour unicolour)
    {
        var expected = HexLookup[name].ToUpper();
        Assert.That(unicolour.Hex, Is.EqualTo(expected));
    }

    [Test] // not 954!
    public void All()
    {
        Assert.That(Xkcd.All.Count(), Is.EqualTo(949));
        Assert.That(Xkcd.All.Distinct().Count(), Is.EqualTo(949));
    }
    
    private static readonly List<string> Names = HexLookup.Keys.ToList();

    [Test]
    public void Name([ValueSource(nameof(Names))] string name)
    {
        var unicolour = FromName(name);
        Assert.That(unicolour, Is.Not.Null);
        
        var expected = HexLookup[name].ToUpper();
        Assert.That(unicolour!.Hex, Is.EqualTo(expected));
    }

    private static readonly List<string> TransformedNames = Names.Select(AddWhitespaceAndUppercase).ToList();
    private static string AddWhitespaceAndUppercase(string text)
    {
        var multicase = string.Concat(text.Select((x, i) => i % 2 == 0 ? char.ToLower(x) : char.ToUpper(x)));
        return multicase.Insert(multicase.Length, "\n").Insert(multicase.Length - 1, " ").Insert(0, "\t").Insert(2, " ");
    }
    
    [Test]
    public void NameWithWhitespaceAndCasing([ValueSource(nameof(TransformedNames))] string name)
    {
        var unicolour = FromName(name);
        Assert.That(unicolour, Is.Not.Null);
    }

    [TestCase("bubblegumpink")] // could be either "bubblegum pink" or "bubble gum pink"
    [TestCase("pinkpurple")] // could be either "pink purple" or "pink/purple"
    [TestCase("yellow\tgreen")] // could be either "yellow green", "yellowgreen", or "yellow/green"
    public void NameWithMultipleMatches(string name)
    {
        var unicolour = FromName(name);
        Assert.That(unicolour, Is.Not.Null);
    }
    
    // names that look like they should exist based on other names
    [TestCase("light goldenrod")]
    [TestCase("goldenrod yellow")]
    [TestCase("medium goldenrod")]
    [TestCase("medium red")]
    [TestCase("vermilion")] // "vermillion" in this dataset
    // misspellings
    [TestCase("biege")]
    [TestCase("chartruese")]
    [TestCase("dodgeblue")]
    [TestCase("gray")] // 😉
    [TestCase("orang")]
    [TestCase("stealblue")]
    [TestCase("tourquise")]
    // common text and numbers
    [TestCase("unicolour")]
    [TestCase("abc")]
    [TestCase("123")]
    // punctuation and whitespace
    [TestCase("\"acid green\"")]
    [TestCase(".")]
    [TestCase(" ")]
    [TestCase("")]
    [TestCase("\t")]
    [TestCase("\n")]
    [TestCase(null)]
    public void NameNotFound(string name)
    {
        var unicolour = FromName(name);
        Assert.That(unicolour, Is.Null);
    }
}