using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using Wacton.Unicolour.Datasets;
using static Wacton.Unicolour.Datasets.Xkcd;

namespace Wacton.Unicolour.Tests;

public class DatasetXkcdTests
{
    // https://xkcd.com/color/rgb.txt
    private static readonly Dictionary<string, string> HexLookup = new()
    {
        { "acid green", "#8ffe09" }, 
        { "adobe", "#bd6c48" }, 
        { "algae green", "#21c36f" }, 
        { "algae", "#54ac68" }, 
        { "almost black", "#070d0d" }, 
        { "amber", "#feb308" }, 
        { "amethyst", "#9b5fc0" }, 
        { "apple green", "#76cd26" }, 
        { "apple", "#6ecb3c" }, 
        { "apricot", "#ffb16d" }, 
        { "aqua blue", "#02d8e9" }, 
        { "aqua green", "#12e193" }, 
        { "aqua marine", "#2ee8bb" }, 
        { "aqua", "#13eac9" }, 
        { "aquamarine", "#04d8b2" }, 
        { "army green", "#4b5d16" }, 
        { "asparagus", "#77ab56" }, 
        { "aubergine", "#3d0734" }, 
        { "auburn", "#9a3001" }, 
        { "avocado green", "#87a922" }, 
        { "avocado", "#90b134" }, 
        { "azul", "#1d5dec" }, 
        { "azure", "#069af3" }, 
        { "baby blue", "#a2cffe" }, 
        { "baby green", "#8cff9e" }, 
        { "baby pink", "#ffb7ce" }, 
        { "baby poo", "#ab9004" }, 
        { "baby poop green", "#8f9805" }, 
        { "baby poop", "#937c00" }, 
        { "baby puke green", "#b6c406" }, 
        { "baby purple", "#ca9bf7" }, 
        { "baby shit brown", "#ad900d" }, 
        { "baby shit green", "#889717" }, 
        { "banana yellow", "#fafe4b" }, 
        { "banana", "#ffff7e" }, 
        { "barbie pink", "#fe46a5" }, 
        { "barf green", "#94ac02" }, 
        { "barney purple", "#a00498" }, 
        { "barney", "#ac1db8" }, 
        { "battleship grey", "#6b7c85" }, 
        { "beige", "#e6daa6" }, 
        { "berry", "#990f4b" }, 
        { "bile", "#b5c306" }, 
        { "black", "#000000" }, 
        { "bland", "#afa88b" }, 
        { "blood orange", "#fe4b03" }, 
        { "blood red", "#980002" }, 
        { "blood", "#770001" }, 
        { "blue blue", "#2242c7" }, 
        { "blue green", "#137e6d" }, 
        { "blue grey", "#607c8e" }, 
        { "blue purple", "#5729ce" }, 
        { "blue violet", "#5d06e9" }, 
        { "blue with a hint of purple", "#533cc6" }, 
        { "blue", "#0343df" }, 
        { "blue/green", "#0f9b8e" }, 
        { "blue/grey", "#758da3" }, 
        { "blue/purple", "#5a06ef" }, 
        { "blueberry", "#464196" }, 
        { "bluegreen", "#017a79" }, 
        { "bluegrey", "#85a3b2" }, 
        { "bluey green", "#2bb179" }, 
        { "bluey grey", "#89a0b0" }, 
        { "bluey purple", "#6241c7" }, 
        { "bluish green", "#10a674" }, 
        { "bluish grey", "#748b97" }, 
        { "bluish purple", "#703be7" }, 
        { "bluish", "#2976bb" }, 
        { "blurple", "#5539cc" }, 
        { "blush pink", "#fe828c" }, 
        { "blush", "#f29e8e" }, 
        { "booger green", "#96b403" }, 
        { "booger", "#9bb53c" }, 
        { "bordeaux", "#7b002c" }, 
        { "boring green", "#63b365" }, 
        { "bottle green", "#044a05" }, 
        { "brick orange", "#c14a09" }, 
        { "brick red", "#8f1402" }, 
        { "brick", "#a03623" }, 
        { "bright aqua", "#0bf9ea" }, 
        { "bright blue", "#0165fc" }, 
        { "bright cyan", "#41fdfe" }, 
        { "bright green", "#01ff07" }, 
        { "bright lavender", "#c760ff" }, 
        { "bright light blue", "#26f7fd" }, 
        { "bright light green", "#2dfe54" }, 
        { "bright lilac", "#c95efb" }, 
        { "bright lime green", "#65fe08" }, 
        { "bright lime", "#87fd05" }, 
        { "bright magenta", "#ff08e8" }, 
        { "bright olive", "#9cbb04" }, 
        { "bright orange", "#ff5b00" }, 
        { "bright pink", "#fe01b1" }, 
        { "bright purple", "#be03fd" }, 
        { "bright red", "#ff000d" }, 
        { "bright sea green", "#05ffa6" }, 
        { "bright sky blue", "#02ccfe" }, 
        { "bright teal", "#01f9c6" }, 
        { "bright turquoise", "#0ffef9" }, 
        { "bright violet", "#ad0afd" }, 
        { "bright yellow green", "#9dff00" }, 
        { "bright yellow", "#fffd01" }, 
        { "british racing green", "#05480d" }, 
        { "bronze", "#a87900" }, 
        { "brown green", "#706c11" }, 
        { "brown grey", "#8d8468" }, 
        { "brown orange", "#b96902" }, 
        { "brown red", "#922b05" }, 
        { "brown yellow", "#b29705" }, 
        { "brown", "#653700" }, 
        { "brownish green", "#6a6e09" }, 
        { "brownish grey", "#86775f" }, 
        { "brownish orange", "#cb7723" }, 
        { "brownish pink", "#c27e79" }, 
        { "brownish purple", "#76424e" }, 
        { "brownish red", "#9e3623" }, 
        { "brownish yellow", "#c9b003" }, 
        { "brownish", "#9c6d57" }, 
        { "browny green", "#6f6c0a" }, 
        { "browny orange", "#ca6b02" }, 
        { "bruise", "#7e4071" }, 
        { "bubble gum pink", "#ff69af" }, 
        { "bubblegum pink", "#fe83cc" }, 
        { "bubblegum", "#ff6cb5" }, 
        { "buff", "#fef69e" }, 
        { "burgundy", "#610023" }, 
        { "burnt orange", "#c04e01" }, 
        { "burnt red", "#9f2305" }, 
        { "burnt siena", "#b75203" }, 
        { "burnt sienna", "#b04e0f" }, 
        { "burnt umber", "#a0450e" }, 
        { "burnt yellow", "#d5ab09" }, 
        { "burple", "#6832e3" }, 
        { "butter yellow", "#fffd74" }, 
        { "butter", "#ffff81" }, 
        { "butterscotch", "#fdb147" }, 
        { "cadet blue", "#4e7496" }, 
        { "camel", "#c69f59" }, 
        { "camo green", "#526525" }, 
        { "camo", "#7f8f4e" }, 
        { "camouflage green", "#4b6113" }, 
        { "canary yellow", "#fffe40" }, 
        { "canary", "#fdff63" }, 
        { "candy pink", "#ff63e9" }, 
        { "caramel", "#af6f09" }, 
        { "carmine", "#9d0216" }, 
        { "carnation pink", "#ff7fa7" }, 
        { "carnation", "#fd798f" }, 
        { "carolina blue", "#8ab8fe" }, 
        { "celadon", "#befdb7" }, 
        { "celery", "#c1fd95" }, 
        { "cement", "#a5a391" }, 
        { "cerise", "#de0c62" }, 
        { "cerulean blue", "#056eee" }, 
        { "cerulean", "#0485d1" }, 
        { "charcoal grey", "#3c4142" }, 
        { "charcoal", "#343837" }, 
        { "chartreuse", "#c1f80a" }, 
        { "cherry red", "#f7022a" }, 
        { "cherry", "#cf0234" }, 
        { "chestnut", "#742802" }, 
        { "chocolate brown", "#411900" }, 
        { "chocolate", "#3d1c02" }, 
        { "cinnamon", "#ac4f06" }, 
        { "claret", "#680018" }, 
        { "clay brown", "#b2713d" }, 
        { "clay", "#b66a50" }, 
        { "clear blue", "#247afd" }, 
        { "cloudy blue", "#acc2d9" }, 
        { "cobalt blue", "#030aa7" }, 
        { "cobalt", "#1e488f" }, 
        { "cocoa", "#875f42" }, 
        { "coffee", "#a6814c" }, 
        { "cool blue", "#4984b8" }, 
        { "cool green", "#33b864" }, 
        { "cool grey", "#95a3a6" }, 
        { "copper", "#b66325" }, 
        { "coral pink", "#ff6163" }, 
        { "coral", "#fc5a50" }, 
        { "cornflower blue", "#5170d7" }, 
        { "cornflower", "#6a79f7" }, 
        { "cranberry", "#9e003a" }, 
        { "cream", "#ffffc2" }, 
        { "creme", "#ffffb6" }, 
        { "crimson", "#8c000f" }, 
        { "custard", "#fffd78" }, 
        { "cyan", "#00ffff" }, 
        { "dandelion", "#fedf08" }, 
        { "dark aqua", "#05696b" }, 
        { "dark aquamarine", "#017371" }, 
        { "dark beige", "#ac9362" }, 
        { "dark blue green", "#005249" }, 
        { "dark blue grey", "#1f3b4d" }, 
        { "dark blue", "#00035b" }, 
        { "dark brown", "#341c02" }, 
        { "dark coral", "#cf524e" }, 
        { "dark cream", "#fff39a" }, 
        { "dark cyan", "#0a888a" }, 
        { "dark forest green", "#002d04" }, 
        { "dark fuchsia", "#9d0759" }, 
        { "dark gold", "#b59410" }, 
        { "dark grass green", "#388004" }, 
        { "dark green blue", "#1f6357" }, 
        { "dark green", "#033500" }, 
        { "dark grey blue", "#29465b" }, 
        { "dark grey", "#363737" }, 
        { "dark hot pink", "#d90166" }, 
        { "dark indigo", "#1f0954" }, 
        { "dark khaki", "#9b8f55" }, 
        { "dark lavender", "#856798" }, 
        { "dark lilac", "#9c6da5" }, 
        { "dark lime green", "#7ebd01" }, 
        { "dark lime", "#84b701" }, 
        { "dark magenta", "#960056" }, 
        { "dark maroon", "#3c0008" }, 
        { "dark mauve", "#874c62" }, 
        { "dark mint green", "#20c073" }, 
        { "dark mint", "#48c072" }, 
        { "dark mustard", "#a88905" }, 
        { "dark navy blue", "#00022e" }, 
        { "dark navy", "#000435" }, 
        { "dark olive green", "#3c4d03" }, 
        { "dark olive", "#373e02" }, 
        { "dark orange", "#c65102" }, 
        { "dark pastel green", "#56ae57" }, 
        { "dark peach", "#de7e5d" }, 
        { "dark periwinkle", "#665fd1" }, 
        { "dark pink", "#cb416b" }, 
        { "dark plum", "#3f012c" }, 
        { "dark purple", "#35063e" }, 
        { "dark red", "#840000" }, 
        { "dark rose", "#b5485d" }, 
        { "dark royal blue", "#02066f" }, 
        { "dark sage", "#598556" }, 
        { "dark salmon", "#c85a53" }, 
        { "dark sand", "#a88f59" }, 
        { "dark sea green", "#11875d" }, 
        { "dark seafoam green", "#3eaf76" }, 
        { "dark seafoam", "#1fb57a" }, 
        { "dark sky blue", "#448ee4" }, 
        { "dark slate blue", "#214761" }, 
        { "dark tan", "#af884a" }, 
        { "dark taupe", "#7f684e" }, 
        { "dark teal", "#014d4e" }, 
        { "dark turquoise", "#045c5a" }, 
        { "dark violet", "#34013f" }, 
        { "dark yellow green", "#728f02" }, 
        { "dark yellow", "#d5b60a" }, 
        { "dark", "#1b2431" }, 
        { "darkblue", "#030764" }, 
        { "darkgreen", "#054907" }, 
        { "darkish blue", "#014182" }, 
        { "darkish green", "#287c37" }, 
        { "darkish pink", "#da467d" }, 
        { "darkish purple", "#751973" }, 
        { "darkish red", "#a90308" }, 
        { "deep aqua", "#08787f" }, 
        { "deep blue", "#040273" }, 
        { "deep brown", "#410200" }, 
        { "deep green", "#02590f" }, 
        { "deep lavender", "#8d5eb7" }, 
        { "deep lilac", "#966ebd" }, 
        { "deep magenta", "#a0025c" }, 
        { "deep orange", "#dc4d01" }, 
        { "deep pink", "#cb0162" }, 
        { "deep purple", "#36013f" }, 
        { "deep red", "#9a0200" }, 
        { "deep rose", "#c74767" }, 
        { "deep sea blue", "#015482" }, 
        { "deep sky blue", "#0d75f8" }, 
        { "deep teal", "#00555a" }, 
        { "deep turquoise", "#017374" }, 
        { "deep violet", "#490648" }, 
        { "denim blue", "#3b5b92" }, 
        { "denim", "#3b638c" }, 
        { "desert", "#ccad60" }, 
        { "diarrhea", "#9f8303" }, 
        { "dirt brown", "#836539" }, 
        { "dirt", "#8a6e45" }, 
        { "dirty blue", "#3f829d" }, 
        { "dirty green", "#667e2c" }, 
        { "dirty orange", "#c87606" }, 
        { "dirty pink", "#ca7b80" }, 
        { "dirty purple", "#734a65" }, 
        { "dirty yellow", "#cdc50a" }, 
        { "dodger blue", "#3e82fc" }, 
        { "drab green", "#749551" }, 
        { "drab", "#828344" }, 
        { "dried blood", "#4b0101" }, 
        { "duck egg blue", "#c3fbf4" }, 
        { "dull blue", "#49759c" }, 
        { "dull brown", "#876e4b" }, 
        { "dull green", "#74a662" }, 
        { "dull orange", "#d8863b" }, 
        { "dull pink", "#d5869d" }, 
        { "dull purple", "#84597e" }, 
        { "dull red", "#bb3f3f" }, 
        { "dull teal", "#5f9e8f" }, 
        { "dull yellow", "#eedc5b" }, 
        { "dusk blue", "#26538d" }, 
        { "dusk", "#4e5481" }, 
        { "dusky blue", "#475f94" }, 
        { "dusky pink", "#cc7a8b" }, 
        { "dusky purple", "#895b7b" }, 
        { "dusky rose", "#ba6873" }, 
        { "dust", "#b2996e" }, 
        { "dusty blue", "#5a86ad" }, 
        { "dusty green", "#76a973" }, 
        { "dusty lavender", "#ac86a8" }, 
        { "dusty orange", "#f0833a" }, 
        { "dusty pink", "#d58a94" }, 
        { "dusty purple", "#825f87" }, 
        { "dusty red", "#b9484e" }, 
        { "dusty rose", "#c0737a" }, 
        { "dusty teal", "#4c9085" }, 
        { "earth", "#a2653e" }, 
        { "easter green", "#8cfd7e" }, 
        { "easter purple", "#c071fe" }, 
        { "ecru", "#feffca" }, 
        { "egg shell", "#fffcc4" }, 
        { "eggplant purple", "#430541" }, 
        { "eggplant", "#380835" }, 
        { "eggshell blue", "#c4fff7" }, 
        { "eggshell", "#ffffd4" }, 
        { "electric blue", "#0652ff" }, 
        { "electric green", "#21fc0d" }, 
        { "electric lime", "#a8ff04" }, 
        { "electric pink", "#ff0490" }, 
        { "electric purple", "#aa23ff" }, 
        { "emerald green", "#028f1e" }, 
        { "emerald", "#01a049" }, 
        { "evergreen", "#05472a" }, 
        { "faded blue", "#658cbb" }, 
        { "faded green", "#7bb274" }, 
        { "faded orange", "#f0944d" }, 
        { "faded pink", "#de9dac" }, 
        { "faded purple", "#916e99" }, 
        { "faded red", "#d3494e" }, 
        { "faded yellow", "#feff7f" }, 
        { "fawn", "#cfaf7b" }, 
        { "fern green", "#548d44" }, 
        { "fern", "#63a950" }, 
        { "fire engine red", "#fe0002" }, 
        { "flat blue", "#3c73a8" }, 
        { "flat green", "#699d4c" }, 
        { "fluorescent green", "#08ff08" }, 
        { "fluro green", "#0aff02" }, 
        { "foam green", "#90fda9" }, 
        { "forest green", "#06470c" }, 
        { "forest", "#0b5509" }, 
        { "forrest green", "#154406" }, 
        { "french blue", "#436bad" }, 
        { "fresh green", "#69d84f" }, 
        { "frog green", "#58bc08" }, 
        { "fuchsia", "#ed0dd9" }, 
        { "gold", "#dbb40c" }, 
        { "golden brown", "#b27a01" }, 
        { "golden rod", "#f9bc08" }, 
        { "golden yellow", "#fec615" }, 
        { "golden", "#f5bf03" }, 
        { "goldenrod", "#fac205" }, 
        { "grape purple", "#5d1451" }, 
        { "grape", "#6c3461" }, 
        { "grapefruit", "#fd5956" }, 
        { "grass green", "#3f9b0b" }, 
        { "grass", "#5cac2d" }, 
        { "grassy green", "#419c03" }, 
        { "green apple", "#5edc1f" }, 
        { "green blue", "#06b48b" }, 
        { "green brown", "#544e03" }, 
        { "green grey", "#77926f" }, 
        { "green teal", "#0cb577" }, 
        { "green yellow", "#c9ff27" }, 
        { "green", "#15b01a" }, 
        { "green/blue", "#01c08d" }, 
        { "green/yellow", "#b5ce08" }, 
        { "greenblue", "#23c48b" }, 
        { "greenish beige", "#c9d179" }, 
        { "greenish blue", "#0b8b87" }, 
        { "greenish brown", "#696112" }, 
        { "greenish cyan", "#2afeb7" }, 
        { "greenish grey", "#96ae8d" }, 
        { "greenish tan", "#bccb7a" }, 
        { "greenish teal", "#32bf84" }, 
        { "greenish turquoise", "#00fbb0" }, 
        { "greenish yellow", "#cdfd02" }, 
        { "greenish", "#40a368" }, 
        { "greeny blue", "#42b395" }, 
        { "greeny brown", "#696006" }, 
        { "greeny grey", "#7ea07a" }, 
        { "greeny yellow", "#c6f808" }, 
        { "grey blue", "#6b8ba4" }, 
        { "grey brown", "#7f7053" }, 
        { "grey green", "#789b73" }, 
        { "grey pink", "#c3909b" }, 
        { "grey purple", "#826d8c" }, 
        { "grey teal", "#5e9b8a" }, 
        { "grey", "#929591" }, 
        { "grey/blue", "#647d8e" }, 
        { "grey/green", "#86a17d" }, 
        { "greyblue", "#77a1b5" }, 
        { "greyish blue", "#5e819d" }, 
        { "greyish brown", "#7a6a4f" }, 
        { "greyish green", "#82a67d" }, 
        { "greyish pink", "#c88d94" }, 
        { "greyish purple", "#887191" }, 
        { "greyish teal", "#719f91" }, 
        { "greyish", "#a8a495" }, 
        { "gross green", "#a0bf16" }, 
        { "gunmetal", "#536267" }, 
        { "hazel", "#8e7618" }, 
        { "heather", "#a484ac" }, 
        { "heliotrope", "#d94ff5" }, 
        { "highlighter green", "#1bfc06" }, 
        { "hospital green", "#9be5aa" }, 
        { "hot green", "#25ff29" }, 
        { "hot magenta", "#f504c9" }, 
        { "hot pink", "#ff028d" }, 
        { "hot purple", "#cb00f5" }, 
        { "hunter green", "#0b4008" }, 
        { "ice blue", "#d7fffe" }, 
        { "ice", "#d6fffa" }, 
        { "icky green", "#8fae22" }, 
        { "indian red", "#850e04" }, 
        { "indigo blue", "#3a18b1" }, 
        { "indigo", "#380282" }, 
        { "iris", "#6258c4" }, 
        { "irish green", "#019529" }, 
        { "ivory", "#ffffcb" }, 
        { "jade green", "#2baf6a" }, 
        { "jade", "#1fa774" }, 
        { "jungle green", "#048243" }, 
        { "kelley green", "#009337" }, 
        { "kelly green", "#02ab2e" }, 
        { "kermit green", "#5cb200" }, 
        { "key lime", "#aeff6e" }, 
        { "khaki green", "#728639" }, 
        { "khaki", "#aaa662" }, 
        { "kiwi green", "#8ee53f" }, 
        { "kiwi", "#9cef43" }, 
        { "lavender blue", "#8b88f8" }, 
        { "lavender pink", "#dd85d7" }, 
        { "lavender", "#c79fef" }, 
        { "lawn green", "#4da409" }, 
        { "leaf green", "#5ca904" }, 
        { "leaf", "#71aa34" }, 
        { "leafy green", "#51b73b" }, 
        { "leather", "#ac7434" }, 
        { "lemon green", "#adf802" }, 
        { "lemon lime", "#bffe28" }, 
        { "lemon yellow", "#fdff38" }, 
        { "lemon", "#fdff52" }, 
        { "lichen", "#8fb67b" }, 
        { "light aqua", "#8cffdb" }, 
        { "light aquamarine", "#7bfdc7" }, 
        { "light beige", "#fffeb6" }, 
        { "light blue green", "#7efbb3" }, 
        { "light blue grey", "#b7c9e2" }, 
        { "light blue", "#95d0fc" }, 
        { "light bluish green", "#76fda8" }, 
        { "light bright green", "#53fe5c" }, 
        { "light brown", "#ad8150" }, 
        { "light burgundy", "#a8415b" }, 
        { "light cyan", "#acfffc" }, 
        { "light eggplant", "#894585" }, 
        { "light forest green", "#4f9153" }, 
        { "light gold", "#fddc5c" }, 
        { "light grass green", "#9af764" }, 
        { "light green blue", "#56fca2" }, 
        { "light green", "#96f97b" }, 
        { "light greenish blue", "#63f7b4" }, 
        { "light grey blue", "#9dbcd4" }, 
        { "light grey green", "#b7e1a1" }, 
        { "light grey", "#d8dcd6" }, 
        { "light indigo", "#6d5acf" }, 
        { "light khaki", "#e6f2a2" }, 
        { "light lavendar", "#efc0fe" }, 
        { "light lavender", "#dfc5fe" }, 
        { "light light blue", "#cafffb" }, 
        { "light light green", "#c8ffb0" }, 
        { "light lilac", "#edc8ff" }, 
        { "light lime green", "#b9ff66" }, 
        { "light lime", "#aefd6c" }, 
        { "light magenta", "#fa5ff7" }, 
        { "light maroon", "#a24857" }, 
        { "light mauve", "#c292a1" }, 
        { "light mint green", "#a6fbb2" }, 
        { "light mint", "#b6ffbb" }, 
        { "light moss green", "#a6c875" }, 
        { "light mustard", "#f7d560" }, 
        { "light navy blue", "#2e5a88" }, 
        { "light navy", "#155084" }, 
        { "light neon green", "#4efd54" }, 
        { "light olive green", "#a4be5c" }, 
        { "light olive", "#acbf69" }, 
        { "light orange", "#fdaa48" }, 
        { "light pastel green", "#b2fba5" }, 
        { "light pea green", "#c4fe82" }, 
        { "light peach", "#ffd8b1" }, 
        { "light periwinkle", "#c1c6fc" }, 
        { "light pink", "#ffd1df" }, 
        { "light plum", "#9d5783" }, 
        { "light purple", "#bf77f6" }, 
        { "light red", "#ff474c" }, 
        { "light rose", "#ffc5cb" }, 
        { "light royal blue", "#3a2efe" }, 
        { "light sage", "#bcecac" }, 
        { "light salmon", "#fea993" }, 
        { "light sea green", "#98f6b0" }, 
        { "light seafoam green", "#a7ffb5" }, 
        { "light seafoam", "#a0febf" }, 
        { "light sky blue", "#c6fcff" }, 
        { "light tan", "#fbeeac" }, 
        { "light teal", "#90e4c1" }, 
        { "light turquoise", "#7ef4cc" }, 
        { "light urple", "#b36ff6" }, 
        { "light violet", "#d6b4fc" }, 
        { "light yellow green", "#ccfd7f" }, 
        { "light yellow", "#fffe7a" }, 
        { "light yellowish green", "#c2ff89" }, 
        { "lightblue", "#7bc8f6" }, 
        { "lighter green", "#75fd63" }, 
        { "lighter purple", "#a55af4" }, 
        { "lightgreen", "#76ff7b" }, 
        { "lightish blue", "#3d7afd" }, 
        { "lightish green", "#61e160" }, 
        { "lightish purple", "#a552e6" }, 
        { "lightish red", "#fe2f4a" }, 
        { "lilac", "#cea2fd" }, 
        { "liliac", "#c48efd" }, 
        { "lime green", "#89fe05" }, 
        { "lime yellow", "#d0fe1d" }, 
        { "lime", "#aaff32" }, 
        { "lipstick red", "#c0022f" }, 
        { "lipstick", "#d5174e" }, 
        { "macaroni and cheese", "#efb435" }, 
        { "magenta", "#c20078" }, 
        { "mahogany", "#4a0100" }, 
        { "maize", "#f4d054" }, 
        { "mango", "#ffa62b" }, 
        { "manilla", "#fffa86" }, 
        { "marigold", "#fcc006" }, 
        { "marine blue", "#01386a" }, 
        { "marine", "#042e60" }, 
        { "maroon", "#650021" }, 
        { "mauve", "#ae7181" }, 
        { "medium blue", "#2c6fbb" }, 
        { "medium brown", "#7f5112" }, 
        { "medium green", "#39ad48" }, 
        { "medium grey", "#7d7f7c" }, 
        { "medium pink", "#f36196" }, 
        { "medium purple", "#9e43a2" }, 
        { "melon", "#ff7855" }, 
        { "merlot", "#730039" }, 
        { "metallic blue", "#4f738e" }, 
        { "mid blue", "#276ab3" }, 
        { "mid green", "#50a747" }, 
        { "midnight blue", "#020035" }, 
        { "midnight purple", "#280137" }, 
        { "midnight", "#03012d" }, 
        { "military green", "#667c3e" }, 
        { "milk chocolate", "#7f4e1e" }, 
        { "mint green", "#8fff9f" }, 
        { "mint", "#9ffeb0" }, 
        { "minty green", "#0bf77d" }, 
        { "mocha", "#9d7651" }, 
        { "moss green", "#658b38" }, 
        { "moss", "#769958" }, 
        { "mossy green", "#638b27" }, 
        { "mud brown", "#60460f" }, 
        { "mud green", "#606602" }, 
        { "mud", "#735c12" }, 
        { "muddy brown", "#886806" }, 
        { "muddy green", "#657432" }, 
        { "muddy yellow", "#bfac05" }, 
        { "mulberry", "#920a4e" }, 
        { "murky green", "#6c7a0e" }, 
        { "mushroom", "#ba9e88" }, 
        { "mustard brown", "#ac7e04" }, 
        { "mustard green", "#a8b504" }, 
        { "mustard yellow", "#d2bd0a" }, 
        { "mustard", "#ceb301" }, 
        { "muted blue", "#3b719f" }, 
        { "muted green", "#5fa052" }, 
        { "muted pink", "#d1768f" }, 
        { "muted purple", "#805b87" }, 
        { "nasty green", "#70b23f" }, 
        { "navy blue", "#001146" }, 
        { "navy green", "#35530a" }, 
        { "navy", "#01153e" }, 
        { "neon blue", "#04d9ff" }, 
        { "neon green", "#0cff0c" }, 
        { "neon pink", "#fe019a" }, 
        { "neon purple", "#bc13fe" }, 
        { "neon red", "#ff073a" }, 
        { "neon yellow", "#cfff04" }, 
        { "nice blue", "#107ab0" }, 
        { "night blue", "#040348" }, 
        { "ocean blue", "#03719c" }, 
        { "ocean green", "#3d9973" }, 
        { "ocean", "#017b92" }, 
        { "ocher", "#bf9b0c" }, 
        { "ochre", "#bf9005" }, 
        { "ocre", "#c69c04" }, 
        { "off blue", "#5684ae" }, 
        { "off green", "#6ba353" }, 
        { "off white", "#ffffe4" }, 
        { "off yellow", "#f1f33f" }, 
        { "old pink", "#c77986" }, 
        { "old rose", "#c87f89" }, 
        { "olive brown", "#645403" }, 
        { "olive drab", "#6f7632" }, 
        { "olive green", "#677a04" }, 
        { "olive yellow", "#c2b709" }, 
        { "olive", "#6e750e" }, 
        { "orange brown", "#be6400" }, 
        { "orange pink", "#ff6f52" }, 
        { "orange red", "#fd411e" }, 
        { "orange yellow", "#ffad01" }, 
        { "orange", "#f97306" }, 
        { "orangeish", "#fd8d49" }, 
        { "orangered", "#fe420f" }, 
        { "orangey brown", "#b16002" }, 
        { "orangey red", "#fa4224" }, 
        { "orangey yellow", "#fdb915" }, 
        { "orangish brown", "#b25f03" }, 
        { "orangish red", "#f43605" }, 
        { "orangish", "#fc824a" }, 
        { "orchid", "#c875c4" }, 
        { "pale aqua", "#b8ffeb" }, 
        { "pale blue", "#d0fefe" }, 
        { "pale brown", "#b1916e" }, 
        { "pale cyan", "#b7fffa" }, 
        { "pale gold", "#fdde6c" }, 
        { "pale green", "#c7fdb5" }, 
        { "pale grey", "#fdfdfe" }, 
        { "pale lavender", "#eecffe" }, 
        { "pale light green", "#b1fc99" }, 
        { "pale lilac", "#e4cbff" }, 
        { "pale lime green", "#b1ff65" }, 
        { "pale lime", "#befd73" }, 
        { "pale magenta", "#d767ad" }, 
        { "pale mauve", "#fed0fc" }, 
        { "pale olive green", "#b1d27b" }, 
        { "pale olive", "#b9cc81" }, 
        { "pale orange", "#ffa756" }, 
        { "pale peach", "#ffe5ad" }, 
        { "pale pink", "#ffcfdc" }, 
        { "pale purple", "#b790d4" }, 
        { "pale red", "#d9544d" }, 
        { "pale rose", "#fdc1c5" }, 
        { "pale salmon", "#ffb19a" }, 
        { "pale sky blue", "#bdf6fe" }, 
        { "pale teal", "#82cbb2" }, 
        { "pale turquoise", "#a5fbd5" }, 
        { "pale violet", "#ceaefa" }, 
        { "pale yellow", "#ffff84" }, 
        { "pale", "#fff9d0" }, 
        { "parchment", "#fefcaf" }, 
        { "pastel blue", "#a2bffe" }, 
        { "pastel green", "#b0ff9d" }, 
        { "pastel orange", "#ff964f" }, 
        { "pastel pink", "#ffbacd" }, 
        { "pastel purple", "#caa0ff" }, 
        { "pastel red", "#db5856" }, 
        { "pastel yellow", "#fffe71" }, 
        { "pea green", "#8eab12" }, 
        { "pea soup green", "#94a617" }, 
        { "pea soup", "#929901" }, 
        { "pea", "#a4bf20" }, 
        { "peach", "#ffb07c" }, 
        { "peachy pink", "#ff9a8a" }, 
        { "peacock blue", "#016795" }, 
        { "pear", "#cbf85f" }, 
        { "periwinkle blue", "#8f99fb" }, 
        { "periwinkle", "#8e82fe" }, 
        { "perrywinkle", "#8f8ce7" }, 
        { "petrol", "#005f6a" }, 
        { "pig pink", "#e78ea5" }, 
        { "pine green", "#0a481e" }, 
        { "pine", "#2b5d34" }, 
        { "pink purple", "#db4bda" }, 
        { "pink red", "#f5054f" }, 
        { "pink", "#ff81c0" }, 
        { "pink/purple", "#ef1de7" }, 
        { "pinkish brown", "#b17261" }, 
        { "pinkish grey", "#c8aca9" }, 
        { "pinkish orange", "#ff724c" }, 
        { "pinkish purple", "#d648d7" }, 
        { "pinkish red", "#f10c45" }, 
        { "pinkish tan", "#d99b82" }, 
        { "pinkish", "#d46a7e" }, 
        { "pinky purple", "#c94cbe" }, 
        { "pinky red", "#fc2647" }, 
        { "pinky", "#fc86aa" }, 
        { "piss yellow", "#ddd618" }, 
        { "pistachio", "#c0fa8b" }, 
        { "plum purple", "#4e0550" }, 
        { "plum", "#580f41" }, 
        { "poison green", "#40fd14" }, 
        { "poo brown", "#885f01" }, 
        { "poo", "#8f7303" }, 
        { "poop brown", "#7a5901" }, 
        { "poop green", "#6f7c00" }, 
        { "poop", "#7f5e00" }, 
        { "powder blue", "#b1d1fc" }, 
        { "powder pink", "#ffb2d0" }, 
        { "primary blue", "#0804f9" }, 
        { "prussian blue", "#004577" }, 
        { "puce", "#a57e52" }, 
        { "puke brown", "#947706" }, 
        { "puke green", "#9aae07" }, 
        { "puke yellow", "#c2be0e" }, 
        { "puke", "#a5a502" }, 
        { "pumpkin orange", "#fb7d07" }, 
        { "pumpkin", "#e17701" }, 
        { "pure blue", "#0203e2" }, 
        { "purple blue", "#632de9" }, 
        { "purple brown", "#673a3f" }, 
        { "purple grey", "#866f85" }, 
        { "purple pink", "#e03fd8" }, 
        { "purple red", "#990147" }, 
        { "purple", "#7e1e9c" }, 
        { "purple/blue", "#5d21d0" }, 
        { "purple/pink", "#d725de" }, 
        { "purpleish blue", "#6140ef" }, 
        { "purpleish pink", "#df4ec8" }, 
        { "purpleish", "#98568d" }, 
        { "purpley blue", "#5f34e7" }, 
        { "purpley grey", "#947e94" }, 
        { "purpley pink", "#c83cb9" }, 
        { "purpley", "#8756e4" }, 
        { "purplish blue", "#601ef9" }, 
        { "purplish brown", "#6b4247" }, 
        { "purplish grey", "#7a687f" }, 
        { "purplish pink", "#ce5dae" }, 
        { "purplish red", "#b0054b" }, 
        { "purplish", "#94568c" }, 
        { "purply blue", "#661aee" }, 
        { "purply pink", "#f075e6" }, 
        { "purply", "#983fb2" }, 
        { "putty", "#beae8a" }, 
        { "racing green", "#014600" }, 
        { "radioactive green", "#2cfa1f" }, 
        { "raspberry", "#b00149" }, 
        { "raw sienna", "#9a6200" }, 
        { "raw umber", "#a75e09" }, 
        { "really light blue", "#d4ffff" }, 
        { "red brown", "#8b2e16" }, 
        { "red orange", "#fd3c06" }, 
        { "red pink", "#fa2a55" }, 
        { "red purple", "#820747" }, 
        { "red violet", "#9e0168" }, 
        { "red wine", "#8c0034" }, 
        { "red", "#e50000" }, 
        { "reddish brown", "#7f2b0a" }, 
        { "reddish grey", "#997570" }, 
        { "reddish orange", "#f8481c" }, 
        { "reddish pink", "#fe2c54" }, 
        { "reddish purple", "#910951" }, 
        { "reddish", "#c44240" }, 
        { "reddy brown", "#6e1005" }, 
        { "rich blue", "#021bf9" }, 
        { "rich purple", "#720058" }, 
        { "robin egg blue", "#8af1fe" }, 
        { "robin's egg blue", "#98eff9" }, 
        { "robin's egg", "#6dedfd" }, 
        { "rosa", "#fe86a4" }, 
        { "rose pink", "#f7879a" }, 
        { "rose red", "#be013c" }, 
        { "rose", "#cf6275" }, 
        { "rosy pink", "#f6688e" }, 
        { "rouge", "#ab1239" }, 
        { "royal blue", "#0504aa" }, 
        { "royal purple", "#4b006e" }, 
        { "royal", "#0c1793" }, 
        { "ruby", "#ca0147" }, 
        { "russet", "#a13905" }, 
        { "rust brown", "#8b3103" }, 
        { "rust orange", "#c45508" }, 
        { "rust red", "#aa2704" }, 
        { "rust", "#a83c09" }, 
        { "rusty orange", "#cd5909" }, 
        { "rusty red", "#af2f0d" }, 
        { "saffron", "#feb209" }, 
        { "sage green", "#88b378" }, 
        { "sage", "#87ae73" }, 
        { "salmon pink", "#fe7b7c" }, 
        { "salmon", "#ff796c" }, 
        { "sand brown", "#cba560" }, 
        { "sand yellow", "#fce166" }, 
        { "sand", "#e2ca76" }, 
        { "sandstone", "#c9ae74" }, 
        { "sandy brown", "#c4a661" }, 
        { "sandy yellow", "#fdee73" }, 
        { "sandy", "#f1da7a" }, 
        { "sap green", "#5c8b15" }, 
        { "sapphire", "#2138ab" }, 
        { "scarlet", "#be0119" }, 
        { "sea blue", "#047495" }, 
        { "sea green", "#53fca1" }, 
        { "sea", "#3c9992" }, 
        { "seafoam blue", "#78d1b6" }, 
        { "seafoam green", "#7af9ab" }, 
        { "seafoam", "#80f9ad" }, 
        { "seaweed green", "#35ad6b" }, 
        { "seaweed", "#18d17b" }, 
        { "sepia", "#985e2b" }, 
        { "shamrock green", "#02c14d" }, 
        { "shamrock", "#01b44c" }, 
        { "shit brown", "#7b5804" }, 
        { "shit green", "#758000" }, 
        { "shit", "#7f5f00" }, 
        { "shocking pink", "#fe02a2" }, 
        { "sick green", "#9db92c" }, 
        { "sickly green", "#94b21c" }, 
        { "sickly yellow", "#d0e429" }, 
        { "sienna", "#a9561e" }, 
        { "silver", "#c5c9c7" }, 
        { "sky blue", "#75bbfd" }, 
        { "sky", "#82cafc" }, 
        { "slate blue", "#5b7c99" }, 
        { "slate green", "#658d6d" }, 
        { "slate grey", "#59656d" }, 
        { "slate", "#516572" }, 
        { "slime green", "#99cc04" }, 
        { "snot green", "#9dc100" }, 
        { "snot", "#acbb0d" }, 
        { "soft blue", "#6488ea" }, 
        { "soft green", "#6fc276" }, 
        { "soft pink", "#fdb0c0" }, 
        { "soft purple", "#a66fb5" }, 
        { "spearmint", "#1ef876" }, 
        { "spring green", "#a9f971" }, 
        { "spruce", "#0a5f38" }, 
        { "squash", "#f2ab15" }, 
        { "steel blue", "#5a7d9a" }, 
        { "steel grey", "#6f828a" }, 
        { "steel", "#738595" }, 
        { "stone", "#ada587" }, 
        { "stormy blue", "#507b9c" }, 
        { "straw", "#fcf679" }, 
        { "strawberry", "#fb2943" }, 
        { "strong blue", "#0c06f7" }, 
        { "strong pink", "#ff0789" }, 
        { "sun yellow", "#ffdf22" }, 
        { "sunflower yellow", "#ffda03" }, 
        { "sunflower", "#ffc512" }, 
        { "sunny yellow", "#fff917" }, 
        { "sunshine yellow", "#fffd37" }, 
        { "swamp green", "#748500" }, 
        { "swamp", "#698339" }, 
        { "tan brown", "#ab7e4c" }, 
        { "tan green", "#a9be70" }, 
        { "tan", "#d1b26f" }, 
        { "tangerine", "#ff9408" }, 
        { "taupe", "#b9a281" }, 
        { "tea green", "#bdf8a3" }, 
        { "tea", "#65ab7c" }, 
        { "teal blue", "#01889f" }, 
        { "teal green", "#25a36f" }, 
        { "teal", "#029386" }, 
        { "tealish green", "#0cdc73" }, 
        { "tealish", "#24bca8" }, 
        { "terra cotta", "#c9643b" }, 
        { "terracota", "#cb6843" }, 
        { "terracotta", "#ca6641" }, 
        { "tiffany blue", "#7bf2da" }, 
        { "tomato red", "#ec2d01" }, 
        { "tomato", "#ef4026" }, 
        { "topaz", "#13bbaf" }, 
        { "toupe", "#c7ac7d" }, 
        { "toxic green", "#61de2a" }, 
        { "tree green", "#2a7e19" }, 
        { "true blue", "#010fcc" }, 
        { "true green", "#089404" }, 
        { "turquoise blue", "#06b1c4" }, 
        { "turquoise green", "#04f489" }, 
        { "turquoise", "#06c2ac" }, 
        { "turtle green", "#75b84f" }, 
        { "twilight blue", "#0a437a" }, 
        { "twilight", "#4e518b" }, 
        { "ugly blue", "#31668a" }, 
        { "ugly brown", "#7d7103" }, 
        { "ugly green", "#7a9703" }, 
        { "ugly pink", "#cd7584" }, 
        { "ugly purple", "#a442a0" }, 
        { "ugly yellow", "#d0c101" }, 
        { "ultramarine blue", "#1805db" }, 
        { "ultramarine", "#2000b1" }, 
        { "umber", "#b26400" }, 
        { "velvet", "#750851" }, 
        { "vermillion", "#f4320c" }, 
        { "very dark blue", "#000133" }, 
        { "very dark brown", "#1d0200" }, 
        { "very dark green", "#062e03" }, 
        { "very dark purple", "#2a0134" }, 
        { "very light blue", "#d5ffff" }, 
        { "very light brown", "#d3b683" }, 
        { "very light green", "#d1ffbd" }, 
        { "very light pink", "#fff4f2" }, 
        { "very light purple", "#f6cefc" }, 
        { "very pale blue", "#d6fffe" }, 
        { "very pale green", "#cffdbc" }, 
        { "vibrant blue", "#0339f8" }, 
        { "vibrant green", "#0add08" }, 
        { "vibrant purple", "#ad03de" }, 
        { "violet blue", "#510ac9" }, 
        { "violet pink", "#fb5ffc" }, 
        { "violet red", "#a50055" }, 
        { "violet", "#9a0eea" }, 
        { "viridian", "#1e9167" }, 
        { "vivid blue", "#152eff" }, 
        { "vivid green", "#2fef10" }, 
        { "vivid purple", "#9900fa" }, 
        { "vomit green", "#89a203" }, 
        { "vomit yellow", "#c7c10c" }, 
        { "vomit", "#a2a415" }, 
        { "warm blue", "#4b57db" }, 
        { "warm brown", "#964e02" }, 
        { "warm grey", "#978a84" }, 
        { "warm pink", "#fb5581" }, 
        { "warm purple", "#952e8f" }, 
        { "washed out green", "#bcf5a6" }, 
        { "water blue", "#0e87cc" }, 
        { "watermelon", "#fd4659" }, 
        { "weird green", "#3ae57f" }, 
        { "wheat", "#fbdd7e" }, 
        { "white", "#ffffff" }, 
        { "windows blue", "#3778bf" }, 
        { "wine red", "#7b0323" }, 
        { "wine", "#80013f" }, 
        { "wintergreen", "#20f986" }, 
        { "wisteria", "#a87dc2" }, 
        { "yellow brown", "#b79400" }, 
        { "yellow green", "#c0fb2d" }, 
        { "yellow ochre", "#cb9d06" }, 
        { "yellow orange", "#fcb001" }, 
        { "yellow tan", "#ffe36e" }, 
        { "yellow", "#ffff14" }, 
        { "yellow/green", "#c8fd3d" }, 
        { "yellowgreen", "#bbf90f" }, 
        { "yellowish brown", "#9b7a01" }, 
        { "yellowish green", "#b0dd16" }, 
        { "yellowish orange", "#ffab0f" }, 
        { "yellowish tan", "#fcfc81" }, 
        { "yellowish", "#faee66" }, 
        { "yellowy brown", "#ae8b0c" }, 
        { "yellowy green", "#bff128" }
    };
    
    private static readonly List<TestCaseData> HexTestData =
    [
        new("acid green", AcidGreen),
        new("adobe", Adobe),
        new("algae green", AlgaeGreen),
        new("algae", Algae),
        new("almost black", AlmostBlack),
        new("amber", Amber),
        new("amethyst", Amethyst),
        new("apple green", AppleGreen),
        new("apple", Apple),
        new("apricot", Apricot),
        new("aqua blue", AquaBlue),
        new("aqua green", AquaGreen),
        new("aqua marine", AquaMarine),
        new("aqua", Aqua),
        new("aquamarine", Aquamarine),
        new("army green", ArmyGreen),
        new("asparagus", Asparagus),
        new("aubergine", Aubergine),
        new("auburn", Auburn),
        new("avocado green", AvocadoGreen),
        new("avocado", Avocado),
        new("azul", Azul),
        new("azure", Azure),
        new("baby blue", BabyBlue),
        new("baby green", BabyGreen),
        new("baby pink", BabyPink),
        new("baby poo", BabyPoo),
        new("baby poop green", BabyPoopGreen),
        new("baby poop", BabyPoop),
        new("baby puke green", BabyPukeGreen),
        new("baby purple", BabyPurple),
        new("baby shit brown", BabyShitBrown),
        new("baby shit green", BabyShitGreen),
        new("banana yellow", BananaYellow),
        new("banana", Banana),
        new("barbie pink", BarbiePink),
        new("barf green", BarfGreen),
        new("barney purple", BarneyPurple),
        new("barney", Barney),
        new("battleship grey", BattleshipGrey),
        new("beige", Beige),
        new("berry", Berry),
        new("bile", Bile),
        new("black", Black),
        new("bland", Bland),
        new("blood orange", BloodOrange),
        new("blood red", BloodRed),
        new("blood", Blood),
        new("blue blue", BlueBlue),
        new("blue green", BlueGreen),
        new("blue grey", BlueGrey),
        new("blue purple", BluePurple),
        new("blue violet", BlueViolet),
        new("blue with a hint of purple", BlueWithAHintOfPurple),
        new("blue", Blue),
        new("blue/green", Blue_Green),
        new("blue/grey", Blue_Grey),
        new("blue/purple", Blue_Purple),
        new("blueberry", Blueberry),
        new("bluegreen", Bluegreen),
        new("bluegrey", Bluegrey),
        new("bluey green", BlueyGreen),
        new("bluey grey", BlueyGrey),
        new("bluey purple", BlueyPurple),
        new("bluish green", BluishGreen),
        new("bluish grey", BluishGrey),
        new("bluish purple", BluishPurple),
        new("bluish", Bluish),
        new("blurple", Blurple),
        new("blush pink", BlushPink),
        new("blush", Blush),
        new("booger green", BoogerGreen),
        new("booger", Booger),
        new("bordeaux", Bordeaux),
        new("boring green", BoringGreen),
        new("bottle green", BottleGreen),
        new("brick orange", BrickOrange),
        new("brick red", BrickRed),
        new("brick", Brick),
        new("bright aqua", BrightAqua),
        new("bright blue", BrightBlue),
        new("bright cyan", BrightCyan),
        new("bright green", BrightGreen),
        new("bright lavender", BrightLavender),
        new("bright light blue", BrightLightBlue),
        new("bright light green", BrightLightGreen),
        new("bright lilac", BrightLilac),
        new("bright lime green", BrightLimeGreen),
        new("bright lime", BrightLime),
        new("bright magenta", BrightMagenta),
        new("bright olive", BrightOlive),
        new("bright orange", BrightOrange),
        new("bright pink", BrightPink),
        new("bright purple", BrightPurple),
        new("bright red", BrightRed),
        new("bright sea green", BrightSeaGreen),
        new("bright sky blue", BrightSkyBlue),
        new("bright teal", BrightTeal),
        new("bright turquoise", BrightTurquoise),
        new("bright violet", BrightViolet),
        new("bright yellow green", BrightYellowGreen),
        new("bright yellow", BrightYellow),
        new("british racing green", BritishRacingGreen),
        new("bronze", Bronze),
        new("brown green", BrownGreen),
        new("brown grey", BrownGrey),
        new("brown orange", BrownOrange),
        new("brown red", BrownRed),
        new("brown yellow", BrownYellow),
        new("brown", Brown),
        new("brownish green", BrownishGreen),
        new("brownish grey", BrownishGrey),
        new("brownish orange", BrownishOrange),
        new("brownish pink", BrownishPink),
        new("brownish purple", BrownishPurple),
        new("brownish red", BrownishRed),
        new("brownish yellow", BrownishYellow),
        new("brownish", Brownish),
        new("browny green", BrownyGreen),
        new("browny orange", BrownyOrange),
        new("bruise", Bruise),
        new("bubble gum pink", BubbleGumPink),
        new("bubblegum pink", BubblegumPink),
        new("bubblegum", Bubblegum),
        new("buff", Buff),
        new("burgundy", Burgundy),
        new("burnt orange", BurntOrange),
        new("burnt red", BurntRed),
        new("burnt siena", BurntSiena),
        new("burnt sienna", BurntSienna),
        new("burnt umber", BurntUmber),
        new("burnt yellow", BurntYellow),
        new("burple", Burple),
        new("butter yellow", ButterYellow),
        new("butter", Butter),
        new("butterscotch", Butterscotch),
        new("cadet blue", CadetBlue),
        new("camel", Camel),
        new("camo green", CamoGreen),
        new("camo", Camo),
        new("camouflage green", CamouflageGreen),
        new("canary yellow", CanaryYellow),
        new("canary", Canary),
        new("candy pink", CandyPink),
        new("caramel", Caramel),
        new("carmine", Carmine),
        new("carnation pink", CarnationPink),
        new("carnation", Carnation),
        new("carolina blue", CarolinaBlue),
        new("celadon", Celadon),
        new("celery", Celery),
        new("cement", Cement),
        new("cerise", Cerise),
        new("cerulean blue", CeruleanBlue),
        new("cerulean", Cerulean),
        new("charcoal grey", CharcoalGrey),
        new("charcoal", Charcoal),
        new("chartreuse", Chartreuse),
        new("cherry red", CherryRed),
        new("cherry", Cherry),
        new("chestnut", Chestnut),
        new("chocolate brown", ChocolateBrown),
        new("chocolate", Chocolate),
        new("cinnamon", Cinnamon),
        new("claret", Claret),
        new("clay brown", ClayBrown),
        new("clay", Clay),
        new("clear blue", ClearBlue),
        new("cloudy blue", CloudyBlue),
        new("cobalt blue", CobaltBlue),
        new("cobalt", Cobalt),
        new("cocoa", Cocoa),
        new("coffee", Coffee),
        new("cool blue", CoolBlue),
        new("cool green", CoolGreen),
        new("cool grey", CoolGrey),
        new("copper", Copper),
        new("coral pink", CoralPink),
        new("coral", Coral),
        new("cornflower blue", CornflowerBlue),
        new("cornflower", Cornflower),
        new("cranberry", Cranberry),
        new("cream", Cream),
        new("creme", Creme),
        new("crimson", Crimson),
        new("custard", Custard),
        new("cyan", Cyan),
        new("dandelion", Dandelion),
        new("dark aqua", DarkAqua),
        new("dark aquamarine", DarkAquamarine),
        new("dark beige", DarkBeige),
        new("dark blue green", DarkBlueGreen),
        new("dark blue grey", DarkBlueGrey),
        new("dark blue", DarkBlue),
        new("dark brown", DarkBrown),
        new("dark coral", DarkCoral),
        new("dark cream", DarkCream),
        new("dark cyan", DarkCyan),
        new("dark forest green", DarkForestGreen),
        new("dark fuchsia", DarkFuchsia),
        new("dark gold", DarkGold),
        new("dark grass green", DarkGrassGreen),
        new("dark green blue", DarkGreenBlue),
        new("dark green", DarkGreen),
        new("dark grey blue", DarkGreyBlue),
        new("dark grey", DarkGrey),
        new("dark hot pink", DarkHotPink),
        new("dark indigo", DarkIndigo),
        new("dark khaki", DarkKhaki),
        new("dark lavender", DarkLavender),
        new("dark lilac", DarkLilac),
        new("dark lime green", DarkLimeGreen),
        new("dark lime", DarkLime),
        new("dark magenta", DarkMagenta),
        new("dark maroon", DarkMaroon),
        new("dark mauve", DarkMauve),
        new("dark mint green", DarkMintGreen),
        new("dark mint", DarkMint),
        new("dark mustard", DarkMustard),
        new("dark navy blue", DarkNavyBlue),
        new("dark navy", DarkNavy),
        new("dark olive green", DarkOliveGreen),
        new("dark olive", DarkOlive),
        new("dark orange", DarkOrange),
        new("dark pastel green", DarkPastelGreen),
        new("dark peach", DarkPeach),
        new("dark periwinkle", DarkPeriwinkle),
        new("dark pink", DarkPink),
        new("dark plum", DarkPlum),
        new("dark purple", DarkPurple),
        new("dark red", DarkRed),
        new("dark rose", DarkRose),
        new("dark royal blue", DarkRoyalBlue),
        new("dark sage", DarkSage),
        new("dark salmon", DarkSalmon),
        new("dark sand", DarkSand),
        new("dark sea green", DarkSeaGreen),
        new("dark seafoam green", DarkSeafoamGreen),
        new("dark seafoam", DarkSeafoam),
        new("dark sky blue", DarkSkyBlue),
        new("dark slate blue", DarkSlateBlue),
        new("dark tan", DarkTan),
        new("dark taupe", DarkTaupe),
        new("dark teal", DarkTeal),
        new("dark turquoise", DarkTurquoise),
        new("dark violet", DarkViolet),
        new("dark yellow green", DarkYellowGreen),
        new("dark yellow", DarkYellow),
        new("dark", Dark),
        new("darkblue", Darkblue),
        new("darkgreen", Darkgreen),
        new("darkish blue", DarkishBlue),
        new("darkish green", DarkishGreen),
        new("darkish pink", DarkishPink),
        new("darkish purple", DarkishPurple),
        new("darkish red", DarkishRed),
        new("deep aqua", DeepAqua),
        new("deep blue", DeepBlue),
        new("deep brown", DeepBrown),
        new("deep green", DeepGreen),
        new("deep lavender", DeepLavender),
        new("deep lilac", DeepLilac),
        new("deep magenta", DeepMagenta),
        new("deep orange", DeepOrange),
        new("deep pink", DeepPink),
        new("deep purple", DeepPurple),
        new("deep red", DeepRed),
        new("deep rose", DeepRose),
        new("deep sea blue", DeepSeaBlue),
        new("deep sky blue", DeepSkyBlue),
        new("deep teal", DeepTeal),
        new("deep turquoise", DeepTurquoise),
        new("deep violet", DeepViolet),
        new("denim blue", DenimBlue),
        new("denim", Denim),
        new("desert", Desert),
        new("diarrhea", Diarrhea),
        new("dirt brown", DirtBrown),
        new("dirt", Dirt),
        new("dirty blue", DirtyBlue),
        new("dirty green", DirtyGreen),
        new("dirty orange", DirtyOrange),
        new("dirty pink", DirtyPink),
        new("dirty purple", DirtyPurple),
        new("dirty yellow", DirtyYellow),
        new("dodger blue", DodgerBlue),
        new("drab green", DrabGreen),
        new("drab", Drab),
        new("dried blood", DriedBlood),
        new("duck egg blue", DuckEggBlue),
        new("dull blue", DullBlue),
        new("dull brown", DullBrown),
        new("dull green", DullGreen),
        new("dull orange", DullOrange),
        new("dull pink", DullPink),
        new("dull purple", DullPurple),
        new("dull red", DullRed),
        new("dull teal", DullTeal),
        new("dull yellow", DullYellow),
        new("dusk blue", DuskBlue),
        new("dusk", Dusk),
        new("dusky blue", DuskyBlue),
        new("dusky pink", DuskyPink),
        new("dusky purple", DuskyPurple),
        new("dusky rose", DuskyRose),
        new("dust", Dust),
        new("dusty blue", DustyBlue),
        new("dusty green", DustyGreen),
        new("dusty lavender", DustyLavender),
        new("dusty orange", DustyOrange),
        new("dusty pink", DustyPink),
        new("dusty purple", DustyPurple),
        new("dusty red", DustyRed),
        new("dusty rose", DustyRose),
        new("dusty teal", DustyTeal),
        new("earth", Earth),
        new("easter green", EasterGreen),
        new("easter purple", EasterPurple),
        new("ecru", Ecru),
        new("egg shell", EggShell),
        new("eggplant purple", EggplantPurple),
        new("eggplant", Eggplant),
        new("eggshell blue", EggshellBlue),
        new("eggshell", Eggshell),
        new("electric blue", ElectricBlue),
        new("electric green", ElectricGreen),
        new("electric lime", ElectricLime),
        new("electric pink", ElectricPink),
        new("electric purple", ElectricPurple),
        new("emerald green", EmeraldGreen),
        new("emerald", Emerald),
        new("evergreen", Evergreen),
        new("faded blue", FadedBlue),
        new("faded green", FadedGreen),
        new("faded orange", FadedOrange),
        new("faded pink", FadedPink),
        new("faded purple", FadedPurple),
        new("faded red", FadedRed),
        new("faded yellow", FadedYellow),
        new("fawn", Fawn),
        new("fern green", FernGreen),
        new("fern", Fern),
        new("fire engine red", FireEngineRed),
        new("flat blue", FlatBlue),
        new("flat green", FlatGreen),
        new("fluorescent green", FluorescentGreen),
        new("fluro green", FluroGreen),
        new("foam green", FoamGreen),
        new("forest green", ForestGreen),
        new("forest", Forest),
        new("forrest green", ForrestGreen),
        new("french blue", FrenchBlue),
        new("fresh green", FreshGreen),
        new("frog green", FrogGreen),
        new("fuchsia", Fuchsia),
        new("gold", Gold),
        new("golden brown", GoldenBrown),
        new("golden rod", GoldenRod),
        new("golden yellow", GoldenYellow),
        new("golden", Golden),
        new("goldenrod", Goldenrod),
        new("grape purple", GrapePurple),
        new("grape", Grape),
        new("grapefruit", Grapefruit),
        new("grass green", GrassGreen),
        new("grass", Grass),
        new("grassy green", GrassyGreen),
        new("green apple", GreenApple),
        new("green blue", GreenBlue),
        new("green brown", GreenBrown),
        new("green grey", GreenGrey),
        new("green teal", GreenTeal),
        new("green yellow", GreenYellow),
        new("green", Green),
        new("green/blue", Green_Blue),
        new("green/yellow", Green_Yellow),
        new("greenblue", Greenblue),
        new("greenish beige", GreenishBeige),
        new("greenish blue", GreenishBlue),
        new("greenish brown", GreenishBrown),
        new("greenish cyan", GreenishCyan),
        new("greenish grey", GreenishGrey),
        new("greenish tan", GreenishTan),
        new("greenish teal", GreenishTeal),
        new("greenish turquoise", GreenishTurquoise),
        new("greenish yellow", GreenishYellow),
        new("greenish", Greenish),
        new("greeny blue", GreenyBlue),
        new("greeny brown", GreenyBrown),
        new("greeny grey", GreenyGrey),
        new("greeny yellow", GreenyYellow),
        new("grey blue", GreyBlue),
        new("grey brown", GreyBrown),
        new("grey green", GreyGreen),
        new("grey pink", GreyPink),
        new("grey purple", GreyPurple),
        new("grey teal", GreyTeal),
        new("grey", Grey),
        new("grey/blue", Grey_Blue),
        new("grey/green", Grey_Green),
        new("greyblue", Greyblue),
        new("greyish blue", GreyishBlue),
        new("greyish brown", GreyishBrown),
        new("greyish green", GreyishGreen),
        new("greyish pink", GreyishPink),
        new("greyish purple", GreyishPurple),
        new("greyish teal", GreyishTeal),
        new("greyish", Greyish),
        new("gross green", GrossGreen),
        new("gunmetal", Gunmetal),
        new("hazel", Hazel),
        new("heather", Heather),
        new("heliotrope", Heliotrope),
        new("highlighter green", HighlighterGreen),
        new("hospital green", HospitalGreen),
        new("hot green", HotGreen),
        new("hot magenta", HotMagenta),
        new("hot pink", HotPink),
        new("hot purple", HotPurple),
        new("hunter green", HunterGreen),
        new("ice blue", IceBlue),
        new("ice", Ice),
        new("icky green", IckyGreen),
        new("indian red", IndianRed),
        new("indigo blue", IndigoBlue),
        new("indigo", Indigo),
        new("iris", Iris),
        new("irish green", IrishGreen),
        new("ivory", Ivory),
        new("jade green", JadeGreen),
        new("jade", Jade),
        new("jungle green", JungleGreen),
        new("kelley green", KelleyGreen),
        new("kelly green", KellyGreen),
        new("kermit green", KermitGreen),
        new("key lime", KeyLime),
        new("khaki green", KhakiGreen),
        new("khaki", Khaki),
        new("kiwi green", KiwiGreen),
        new("kiwi", Kiwi),
        new("lavender blue", LavenderBlue),
        new("lavender pink", LavenderPink),
        new("lavender", Lavender),
        new("lawn green", LawnGreen),
        new("leaf green", LeafGreen),
        new("leaf", Leaf),
        new("leafy green", LeafyGreen),
        new("leather", Leather),
        new("lemon green", LemonGreen),
        new("lemon lime", LemonLime),
        new("lemon yellow", LemonYellow),
        new("lemon", Lemon),
        new("lichen", Lichen),
        new("light aqua", LightAqua),
        new("light aquamarine", LightAquamarine),
        new("light beige", LightBeige),
        new("light blue green", LightBlueGreen),
        new("light blue grey", LightBlueGrey),
        new("light blue", LightBlue),
        new("light bluish green", LightBluishGreen),
        new("light bright green", LightBrightGreen),
        new("light brown", LightBrown),
        new("light burgundy", LightBurgundy),
        new("light cyan", LightCyan),
        new("light eggplant", LightEggplant),
        new("light forest green", LightForestGreen),
        new("light gold", LightGold),
        new("light grass green", LightGrassGreen),
        new("light green blue", LightGreenBlue),
        new("light green", LightGreen),
        new("light greenish blue", LightGreenishBlue),
        new("light grey blue", LightGreyBlue),
        new("light grey green", LightGreyGreen),
        new("light grey", LightGrey),
        new("light indigo", LightIndigo),
        new("light khaki", LightKhaki),
        new("light lavendar", LightLavendar),
        new("light lavender", LightLavender),
        new("light light blue", LightLightBlue),
        new("light light green", LightLightGreen),
        new("light lilac", LightLilac),
        new("light lime green", LightLimeGreen),
        new("light lime", LightLime),
        new("light magenta", LightMagenta),
        new("light maroon", LightMaroon),
        new("light mauve", LightMauve),
        new("light mint green", LightMintGreen),
        new("light mint", LightMint),
        new("light moss green", LightMossGreen),
        new("light mustard", LightMustard),
        new("light navy blue", LightNavyBlue),
        new("light navy", LightNavy),
        new("light neon green", LightNeonGreen),
        new("light olive green", LightOliveGreen),
        new("light olive", LightOlive),
        new("light orange", LightOrange),
        new("light pastel green", LightPastelGreen),
        new("light pea green", LightPeaGreen),
        new("light peach", LightPeach),
        new("light periwinkle", LightPeriwinkle),
        new("light pink", LightPink),
        new("light plum", LightPlum),
        new("light purple", LightPurple),
        new("light red", LightRed),
        new("light rose", LightRose),
        new("light royal blue", LightRoyalBlue),
        new("light sage", LightSage),
        new("light salmon", LightSalmon),
        new("light sea green", LightSeaGreen),
        new("light seafoam green", LightSeafoamGreen),
        new("light seafoam", LightSeafoam),
        new("light sky blue", LightSkyBlue),
        new("light tan", LightTan),
        new("light teal", LightTeal),
        new("light turquoise", LightTurquoise),
        new("light urple", LightUrple),
        new("light violet", LightViolet),
        new("light yellow green", LightYellowGreen),
        new("light yellow", LightYellow),
        new("light yellowish green", LightYellowishGreen),
        new("lightblue", Lightblue),
        new("lighter green", LighterGreen),
        new("lighter purple", LighterPurple),
        new("lightgreen", Lightgreen),
        new("lightish blue", LightishBlue),
        new("lightish green", LightishGreen),
        new("lightish purple", LightishPurple),
        new("lightish red", LightishRed),
        new("lilac", Lilac),
        new("liliac", Liliac),
        new("lime green", LimeGreen),
        new("lime yellow", LimeYellow),
        new("lime", Lime),
        new("lipstick red", LipstickRed),
        new("lipstick", Lipstick),
        new("macaroni and cheese", MacaroniAndCheese),
        new("magenta", Magenta),
        new("mahogany", Mahogany),
        new("maize", Maize),
        new("mango", Mango),
        new("manilla", Manilla),
        new("marigold", Marigold),
        new("marine blue", MarineBlue),
        new("marine", Marine),
        new("maroon", Maroon),
        new("mauve", Mauve),
        new("medium blue", MediumBlue),
        new("medium brown", MediumBrown),
        new("medium green", MediumGreen),
        new("medium grey", MediumGrey),
        new("medium pink", MediumPink),
        new("medium purple", MediumPurple),
        new("melon", Melon),
        new("merlot", Merlot),
        new("metallic blue", MetallicBlue),
        new("mid blue", MidBlue),
        new("mid green", MidGreen),
        new("midnight blue", MidnightBlue),
        new("midnight purple", MidnightPurple),
        new("midnight", Midnight),
        new("military green", MilitaryGreen),
        new("milk chocolate", MilkChocolate),
        new("mint green", MintGreen),
        new("mint", Mint),
        new("minty green", MintyGreen),
        new("mocha", Mocha),
        new("moss green", MossGreen),
        new("moss", Moss),
        new("mossy green", MossyGreen),
        new("mud brown", MudBrown),
        new("mud green", MudGreen),
        new("mud", Mud),
        new("muddy brown", MuddyBrown),
        new("muddy green", MuddyGreen),
        new("muddy yellow", MuddyYellow),
        new("mulberry", Mulberry),
        new("murky green", MurkyGreen),
        new("mushroom", Mushroom),
        new("mustard brown", MustardBrown),
        new("mustard green", MustardGreen),
        new("mustard yellow", MustardYellow),
        new("mustard", Mustard),
        new("muted blue", MutedBlue),
        new("muted green", MutedGreen),
        new("muted pink", MutedPink),
        new("muted purple", MutedPurple),
        new("nasty green", NastyGreen),
        new("navy blue", NavyBlue),
        new("navy green", NavyGreen),
        new("navy", Navy),
        new("neon blue", NeonBlue),
        new("neon green", NeonGreen),
        new("neon pink", NeonPink),
        new("neon purple", NeonPurple),
        new("neon red", NeonRed),
        new("neon yellow", NeonYellow),
        new("nice blue", NiceBlue),
        new("night blue", NightBlue),
        new("ocean blue", OceanBlue),
        new("ocean green", OceanGreen),
        new("ocean", Ocean),
        new("ocher", Ocher),
        new("ochre", Ochre),
        new("ocre", Ocre),
        new("off blue", OffBlue),
        new("off green", OffGreen),
        new("off white", OffWhite),
        new("off yellow", OffYellow),
        new("old pink", OldPink),
        new("old rose", OldRose),
        new("olive brown", OliveBrown),
        new("olive drab", OliveDrab),
        new("olive green", OliveGreen),
        new("olive yellow", OliveYellow),
        new("olive", Olive),
        new("orange brown", OrangeBrown),
        new("orange pink", OrangePink),
        new("orange red", OrangeRed),
        new("orange yellow", OrangeYellow),
        new("orange", Orange),
        new("orangeish", Orangeish),
        new("orangered", Orangered),
        new("orangey brown", OrangeyBrown),
        new("orangey red", OrangeyRed),
        new("orangey yellow", OrangeyYellow),
        new("orangish brown", OrangishBrown),
        new("orangish red", OrangishRed),
        new("orangish", Orangish),
        new("orchid", Orchid),
        new("pale aqua", PaleAqua),
        new("pale blue", PaleBlue),
        new("pale brown", PaleBrown),
        new("pale cyan", PaleCyan),
        new("pale gold", PaleGold),
        new("pale green", PaleGreen),
        new("pale grey", PaleGrey),
        new("pale lavender", PaleLavender),
        new("pale light green", PaleLightGreen),
        new("pale lilac", PaleLilac),
        new("pale lime green", PaleLimeGreen),
        new("pale lime", PaleLime),
        new("pale magenta", PaleMagenta),
        new("pale mauve", PaleMauve),
        new("pale olive green", PaleOliveGreen),
        new("pale olive", PaleOlive),
        new("pale orange", PaleOrange),
        new("pale peach", PalePeach),
        new("pale pink", PalePink),
        new("pale purple", PalePurple),
        new("pale red", PaleRed),
        new("pale rose", PaleRose),
        new("pale salmon", PaleSalmon),
        new("pale sky blue", PaleSkyBlue),
        new("pale teal", PaleTeal),
        new("pale turquoise", PaleTurquoise),
        new("pale violet", PaleViolet),
        new("pale yellow", PaleYellow),
        new("pale", Pale),
        new("parchment", Parchment),
        new("pastel blue", PastelBlue),
        new("pastel green", PastelGreen),
        new("pastel orange", PastelOrange),
        new("pastel pink", PastelPink),
        new("pastel purple", PastelPurple),
        new("pastel red", PastelRed),
        new("pastel yellow", PastelYellow),
        new("pea green", PeaGreen),
        new("pea soup green", PeaSoupGreen),
        new("pea soup", PeaSoup),
        new("pea", Pea),
        new("peach", Peach),
        new("peachy pink", PeachyPink),
        new("peacock blue", PeacockBlue),
        new("pear", Pear),
        new("periwinkle blue", PeriwinkleBlue),
        new("periwinkle", Periwinkle),
        new("perrywinkle", Perrywinkle),
        new("petrol", Petrol),
        new("pig pink", PigPink),
        new("pine green", PineGreen),
        new("pine", Pine),
        new("pink purple", PinkPurple),
        new("pink red", PinkRed),
        new("pink", Pink),
        new("pink/purple", Pink_Purple),
        new("pinkish brown", PinkishBrown),
        new("pinkish grey", PinkishGrey),
        new("pinkish orange", PinkishOrange),
        new("pinkish purple", PinkishPurple),
        new("pinkish red", PinkishRed),
        new("pinkish tan", PinkishTan),
        new("pinkish", Pinkish),
        new("pinky purple", PinkyPurple),
        new("pinky red", PinkyRed),
        new("pinky", Pinky),
        new("piss yellow", PissYellow),
        new("pistachio", Pistachio),
        new("plum purple", PlumPurple),
        new("plum", Plum),
        new("poison green", PoisonGreen),
        new("poo brown", PooBrown),
        new("poo", Poo),
        new("poop brown", PoopBrown),
        new("poop green", PoopGreen),
        new("poop", Poop),
        new("powder blue", PowderBlue),
        new("powder pink", PowderPink),
        new("primary blue", PrimaryBlue),
        new("prussian blue", PrussianBlue),
        new("puce", Puce),
        new("puke brown", PukeBrown),
        new("puke green", PukeGreen),
        new("puke yellow", PukeYellow),
        new("puke", Puke),
        new("pumpkin orange", PumpkinOrange),
        new("pumpkin", Pumpkin),
        new("pure blue", PureBlue),
        new("purple blue", PurpleBlue),
        new("purple brown", PurpleBrown),
        new("purple grey", PurpleGrey),
        new("purple pink", PurplePink),
        new("purple red", PurpleRed),
        new("purple", Purple),
        new("purple/blue", Purple_Blue),
        new("purple/pink", Purple_Pink),
        new("purpleish blue", PurpleishBlue),
        new("purpleish pink", PurpleishPink),
        new("purpleish", Purpleish),
        new("purpley blue", PurpleyBlue),
        new("purpley grey", PurpleyGrey),
        new("purpley pink", PurpleyPink),
        new("purpley", Purpley),
        new("purplish blue", PurplishBlue),
        new("purplish brown", PurplishBrown),
        new("purplish grey", PurplishGrey),
        new("purplish pink", PurplishPink),
        new("purplish red", PurplishRed),
        new("purplish", Purplish),
        new("purply blue", PurplyBlue),
        new("purply pink", PurplyPink),
        new("purply", Purply),
        new("putty", Putty),
        new("racing green", RacingGreen),
        new("radioactive green", RadioactiveGreen),
        new("raspberry", Raspberry),
        new("raw sienna", RawSienna),
        new("raw umber", RawUmber),
        new("really light blue", ReallyLightBlue),
        new("red brown", RedBrown),
        new("red orange", RedOrange),
        new("red pink", RedPink),
        new("red purple", RedPurple),
        new("red violet", RedViolet),
        new("red wine", RedWine),
        new("red", Red),
        new("reddish brown", ReddishBrown),
        new("reddish grey", ReddishGrey),
        new("reddish orange", ReddishOrange),
        new("reddish pink", ReddishPink),
        new("reddish purple", ReddishPurple),
        new("reddish", Reddish),
        new("reddy brown", ReddyBrown),
        new("rich blue", RichBlue),
        new("rich purple", RichPurple),
        new("robin egg blue", RobinEggBlue),
        new("robin's egg blue", RobinsEggBlue),
        new("robin's egg", RobinsEgg),
        new("rosa", Rosa),
        new("rose pink", RosePink),
        new("rose red", RoseRed),
        new("rose", Rose),
        new("rosy pink", RosyPink),
        new("rouge", Rouge),
        new("royal blue", RoyalBlue),
        new("royal purple", RoyalPurple),
        new("royal", Royal),
        new("ruby", Ruby),
        new("russet", Russet),
        new("rust brown", RustBrown),
        new("rust orange", RustOrange),
        new("rust red", RustRed),
        new("rust", Rust),
        new("rusty orange", RustyOrange),
        new("rusty red", RustyRed),
        new("saffron", Saffron),
        new("sage green", SageGreen),
        new("sage", Sage),
        new("salmon pink", SalmonPink),
        new("salmon", Salmon),
        new("sand brown", SandBrown),
        new("sand yellow", SandYellow),
        new("sand", Sand),
        new("sandstone", Sandstone),
        new("sandy brown", SandyBrown),
        new("sandy yellow", SandyYellow),
        new("sandy", Sandy),
        new("sap green", SapGreen),
        new("sapphire", Sapphire),
        new("scarlet", Scarlet),
        new("sea blue", SeaBlue),
        new("sea green", SeaGreen),
        new("sea", Sea),
        new("seafoam blue", SeafoamBlue),
        new("seafoam green", SeafoamGreen),
        new("seafoam", Seafoam),
        new("seaweed green", SeaweedGreen),
        new("seaweed", Seaweed),
        new("sepia", Sepia),
        new("shamrock green", ShamrockGreen),
        new("shamrock", Shamrock),
        new("shit brown", ShitBrown),
        new("shit green", ShitGreen),
        new("shit", Shit),
        new("shocking pink", ShockingPink),
        new("sick green", SickGreen),
        new("sickly green", SicklyGreen),
        new("sickly yellow", SicklyYellow),
        new("sienna", Sienna),
        new("silver", Silver),
        new("sky blue", SkyBlue),
        new("sky", Sky),
        new("slate blue", SlateBlue),
        new("slate green", SlateGreen),
        new("slate grey", SlateGrey),
        new("slate", Slate),
        new("slime green", SlimeGreen),
        new("snot green", SnotGreen),
        new("snot", Snot),
        new("soft blue", SoftBlue),
        new("soft green", SoftGreen),
        new("soft pink", SoftPink),
        new("soft purple", SoftPurple),
        new("spearmint", Spearmint),
        new("spring green", SpringGreen),
        new("spruce", Spruce),
        new("squash", Squash),
        new("steel blue", SteelBlue),
        new("steel grey", SteelGrey),
        new("steel", Steel),
        new("stone", Stone),
        new("stormy blue", StormyBlue),
        new("straw", Straw),
        new("strawberry", Strawberry),
        new("strong blue", StrongBlue),
        new("strong pink", StrongPink),
        new("sun yellow", SunYellow),
        new("sunflower yellow", SunflowerYellow),
        new("sunflower", Sunflower),
        new("sunny yellow", SunnyYellow),
        new("sunshine yellow", SunshineYellow),
        new("swamp green", SwampGreen),
        new("swamp", Swamp),
        new("tan brown", TanBrown),
        new("tan green", TanGreen),
        new("tan", Tan),
        new("tangerine", Tangerine),
        new("taupe", Taupe),
        new("tea green", TeaGreen),
        new("tea", Tea),
        new("teal blue", TealBlue),
        new("teal green", TealGreen),
        new("teal", Teal),
        new("tealish green", TealishGreen),
        new("tealish", Tealish),
        new("terra cotta", TerraCotta),
        new("terracota", Terracota),
        new("terracotta", Terracotta),
        new("tiffany blue", TiffanyBlue),
        new("tomato red", TomatoRed),
        new("tomato", Tomato),
        new("topaz", Topaz),
        new("toupe", Toupe),
        new("toxic green", ToxicGreen),
        new("tree green", TreeGreen),
        new("true blue", TrueBlue),
        new("true green", TrueGreen),
        new("turquoise blue", TurquoiseBlue),
        new("turquoise green", TurquoiseGreen),
        new("turquoise", Turquoise),
        new("turtle green", TurtleGreen),
        new("twilight blue", TwilightBlue),
        new("twilight", Xkcd.Twilight),
        new("ugly blue", UglyBlue),
        new("ugly brown", UglyBrown),
        new("ugly green", UglyGreen),
        new("ugly pink", UglyPink),
        new("ugly purple", UglyPurple),
        new("ugly yellow", UglyYellow),
        new("ultramarine blue", UltramarineBlue),
        new("ultramarine", Ultramarine),
        new("umber", Umber),
        new("velvet", Velvet),
        new("vermillion", Vermillion),
        new("very dark blue", VeryDarkBlue),
        new("very dark brown", VeryDarkBrown),
        new("very dark green", VeryDarkGreen),
        new("very dark purple", VeryDarkPurple),
        new("very light blue", VeryLightBlue),
        new("very light brown", VeryLightBrown),
        new("very light green", VeryLightGreen),
        new("very light pink", VeryLightPink),
        new("very light purple", VeryLightPurple),
        new("very pale blue", VeryPaleBlue),
        new("very pale green", VeryPaleGreen),
        new("vibrant blue", VibrantBlue),
        new("vibrant green", VibrantGreen),
        new("vibrant purple", VibrantPurple),
        new("violet blue", VioletBlue),
        new("violet pink", VioletPink),
        new("violet red", VioletRed),
        new("violet", Violet),
        new("viridian", Viridian),
        new("vivid blue", VividBlue),
        new("vivid green", VividGreen),
        new("vivid purple", VividPurple),
        new("vomit green", VomitGreen),
        new("vomit yellow", VomitYellow),
        new("vomit", Vomit),
        new("warm blue", WarmBlue),
        new("warm brown", WarmBrown),
        new("warm grey", WarmGrey),
        new("warm pink", WarmPink),
        new("warm purple", WarmPurple),
        new("washed out green", WashedOutGreen),
        new("water blue", WaterBlue),
        new("watermelon", Watermelon),
        new("weird green", WeirdGreen),
        new("wheat", Wheat),
        new("white", White),
        new("windows blue", WindowsBlue),
        new("wine red", WineRed),
        new("wine", Wine),
        new("wintergreen", Wintergreen),
        new("wisteria", Wisteria),
        new("yellow brown", YellowBrown),
        new("yellow green", YellowGreen),
        new("yellow ochre", YellowOchre),
        new("yellow orange", YellowOrange),
        new("yellow tan", YellowTan),
        new("yellow", Yellow),
        new("yellow/green", Yellow_Green),
        new("yellowgreen", Yellowgreen),
        new("yellowish brown", YellowishBrown),
        new("yellowish green", YellowishGreen),
        new("yellowish orange", YellowishOrange),
        new("yellowish tan", YellowishTan),
        new("yellowish", Yellowish),
        new("yellowy brown", YellowyBrown),
        new("yellowy green", YellowyGreen)
    ];

    [TestCaseSource(nameof(HexTestData))]
    public void Hex(string name, Unicolour unicolour)
    {
        var expected = HexLookup[name].ToUpper();
        Assert.That(unicolour.Hex, Is.EqualTo(expected));
    }

    [Test] // not 954!
    public void All()
    {
        Assert.That(Xkcd.All.Count(), Is.EqualTo(949));
        Assert.That(Xkcd.All.Distinct().Count(), Is.EqualTo(949));
    }
    
    private static readonly List<string> Names = HexLookup.Keys.ToList();

    [Test]
    public void Name([ValueSource(nameof(Names))] string name)
    {
        var unicolour = FromName(name);
        Assert.That(unicolour, Is.Not.Null);
        
        var expected = HexLookup[name].ToUpper();
        Assert.That(unicolour!.Hex, Is.EqualTo(expected));
    }

    private static readonly List<string> TransformedNames = Names.Select(AddWhitespaceAndUppercase).ToList();
    private static string AddWhitespaceAndUppercase(string text)
    {
        var multicase = string.Concat(text.Select((x, i) => i % 2 == 0 ? char.ToLower(x) : char.ToUpper(x)));
        return multicase.Insert(multicase.Length, "\n").Insert(multicase.Length - 1, " ").Insert(0, "\t").Insert(2, " ");
    }
    
    [Test]
    public void NameWithWhitespaceAndCasing([ValueSource(nameof(TransformedNames))] string name)
    {
        var unicolour = FromName(name);
        Assert.That(unicolour, Is.Not.Null);
    }

    [TestCase("bubblegumpink")] // could be either "bubblegum pink" or "bubble gum pink"
    [TestCase("pinkpurple")] // could be either "pink purple" or "pink/purple"
    [TestCase("yellow\tgreen")] // could be either "yellow green", "yellowgreen", or "yellow/green"
    public void NameWithMultipleMatches(string name)
    {
        var unicolour = FromName(name);
        Assert.That(unicolour, Is.Not.Null);
    }
    
    // names that look like they should exist based on other names
    [TestCase("light goldenrod")]
    [TestCase("goldenrod yellow")]
    [TestCase("medium goldenrod")]
    [TestCase("medium red")]
    [TestCase("vermilion")] // "vermillion" in this dataset
    // misspellings
    [TestCase("biege")]
    [TestCase("chartruese")]
    [TestCase("dodgeblue")]
    [TestCase("gray")] // 😉
    [TestCase("orang")]
    [TestCase("stealblue")]
    [TestCase("tourquise")]
    // common text and numbers
    [TestCase("unicolour")]
    [TestCase("abc")]
    [TestCase("123")]
    // punctuation and whitespace
    [TestCase("\"acid green\"")]
    [TestCase(".")]
    [TestCase(" ")]
    [TestCase("")]
    [TestCase("\t")]
    [TestCase("\n")]
    [TestCase(null)]
    public void NameNotFound(string name)
    {
        var unicolour = FromName(name);
        Assert.That(unicolour, Is.Null);
    }
}