namespace Wacton.Unicolour;

using System;

public class Unicolour : IEquatable<Unicolour>
{
    public Hsb Hsb { get; }
    public Rgb Rgb => Conversion.HsbToRgb(Hsb);
    public Xyz Xyz => Conversion.RgbToXyz(Rgb);
    public Lab Lab => Conversion.XyzToLab(Xyz);
    public double A { get; }

    public double Luminance => this.Luminance();

    private Unicolour(double h, double s, double b, double a, bool explicitHue)
    {
        Hsb = new Hsb(h, s, b, explicitHue);
        A = a;
    }
    
    public static Unicolour FromHsb(double h, double s, double b, double a = 1.0) => new(h, s, b, a, true);

    public static Unicolour FromRgb(int r, int g, int b, int a = 255) => FromRgb(r / 255.0, g / 255.0, b / 255.0, a / 255.0);
    
    public static Unicolour FromRgb(double r, double g, double b, double a = 1.0)
    {
        var rgb = new Rgb(r, g, b);
        var hsb = Conversion.RgbToHsb(rgb);
        return new Unicolour(hsb.H, hsb.S, hsb.B, a, false);
    }

    public override string ToString() => $"HSB:[{Hsb}] RGB:[{Rgb}] A:{Math.Round(A * 100, 1)}";

    // --- autogenerated ---
    
    public bool Equals(Unicolour? other)
    {
        if (ReferenceEquals(null, other)) return false;
        if (ReferenceEquals(this, other)) return true;
        return Hsb.Equals(other.Hsb) && A.Equals(other.A);
    }

    public override bool Equals(object? obj)
    {
        if (ReferenceEquals(null, obj)) return false;
        if (ReferenceEquals(this, obj)) return true;
        if (obj.GetType() != this.GetType()) return false;
        return Equals((Unicolour) obj);
    }

    public override int GetHashCode()
    {
        unchecked
        {
            return (Hsb.GetHashCode() * 397) ^ A.GetHashCode();
        }
    }
}