namespace Wacton.Unicolour;

using System;

public class Unicolour : IEquatable<Unicolour>
{
    private Hsb? hsb;
    private Rgb? rgb;
    private Xyz? xyz;
    private Lab? lab;

    public Hsb Hsb => hsb ??= Conversion.RgbToHsb(Rgb);
    public Rgb Rgb => rgb ??= Conversion.HsbToRgb(Hsb);
    public Xyz Xyz => xyz ??= Conversion.RgbToXyz(Rgb);
    public Lab Lab => lab ??= Conversion.XyzToLab(Xyz);
    public Alpha Alpha { get; }

    public double Luminance => this.Luminance();

    private Unicolour(Hsb hsb, Alpha alpha)
    {
        this.hsb = hsb;
        Alpha = alpha;
    }
    
    private Unicolour(Rgb rgb, Alpha alpha)
    {
        this.rgb = rgb;
        Alpha = alpha;
    }

    public static Unicolour FromHex(string hex)
    {
        var (r255, g255, b255, a255) = Utils.ParseColourHex(hex);
        return FromRgb255(r255, g255, b255, a255);
    }
    
    public static Unicolour FromRgb255(int r255, int g255, int b255, int a255 = 255) => FromRgb(r255 / 255.0, g255 / 255.0, b255 / 255.0, a255 / 255.0);
    public static Unicolour FromRgb(double r, double g, double b, double a = 1.0) => new(new Rgb(r, g, b), new Alpha(a));
    public static Unicolour FromHsb(double h, double s, double b, double a = 1.0) => new(new Hsb(h, s, b), new Alpha(a));

    public override string ToString() => $"HSB:[{Hsb}] RGB:[{Rgb}] Hex:{Rgb.Hex} A:{Alpha.A}";

    // --- autogenerated ---
    
    public bool Equals(Unicolour? other)
    {
        if (ReferenceEquals(null, other)) return false;
        if (ReferenceEquals(this, other)) return true;
        return Hsb.Equals(other.Hsb) && Alpha.Equals(other.Alpha);
    }

    public override bool Equals(object? obj)
    {
        if (ReferenceEquals(null, obj)) return false;
        if (ReferenceEquals(this, obj)) return true;
        if (obj.GetType() != this.GetType()) return false;
        return Equals((Unicolour) obj);
    }

    public override int GetHashCode()
    {
        unchecked
        {
            return (Hsb.GetHashCode() * 397) ^ Alpha.GetHashCode();
        }
    }
}