<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Wacton.Unicolour.Example.Diagrams</AssemblyName>
    <RootNamespace>Wacton.Unicolour.Example.Diagrams</RootNamespace>
    <LangVersion>default</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <Authors>William Acton</Authors>
    <Product>Wacton.Unicolour.Example.Diagrams</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ScottPlot" Version="5.1.59" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Unicolour.Datasets\Unicolour.Datasets.csproj" />
    <ProjectReference Include="..\Unicolour\Unicolour.csproj" />
  </ItemGroup>

</Project>
